// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Address
 *
 * Address information.
 */
export type Address = {
    /**
     * Addressline
     */
    addressLine?: Array<string> | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Postalcode
     */
    postalCode?: string | null;
    /**
     * Countrycode
     */
    countryCode?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * County
     */
    county?: string | null;
};

/**
 * CancelReason
 *
 * Reason for cancellation.
 */
export type CancelReason = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Code
     */
    code?: string | null;
};

/**
 * CancelReservationDetails
 *
 * Details of a canceled reservation.
 */
export type CancelReservationDetails = {
    /**
     * Reservationidlist
     */
    reservationIdList?: Array<UniqueId> | null;
    cancellationNumber?: UniqueId | null;
    /**
     * Status
     */
    status?: string | null;
};

/**
 * CancelReservationRequest
 *
 * Request to cancel a reservation.
 */
export type CancelReservationRequest = {
    reason?: CancelReason | null;
    /**
     * Reservations
     */
    reservations?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * CheckDistributionReservationsSummary
 *
 * Response wrapper for distribution statistics.
 */
export type CheckDistributionReservationsSummary = {
    /**
     * Checkreservations
     */
    checkReservations?: Array<DistributionReservationSummaryType> | null;
    /**
     * Hasmore
     */
    hasMore?: boolean | null;
};

/**
 * Communications
 *
 * Property communication channels.
 */
export type Communications = {
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ContentPropertyInfo
 *
 * Property information details.
 */
export type ContentPropertyInfo = {
    /**
     * Hotelid
     */
    hotelId?: string | null;
    /**
     * Enterpriseid
     */
    enterpriseId?: string | null;
    /**
     * Hotelcode
     */
    hotelCode?: string | null;
    /**
     * Hotelname
     */
    hotelName?: string | null;
    /**
     * Hoteldescription
     */
    hotelDescription?: string | null;
    /**
     * Chaincode
     */
    chainCode?: string | null;
    /**
     * Clustercode
     */
    clusterCode?: string | null;
    address?: Operaclone2WebApiContentSchemaAddress | null;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
    /**
     * Propertyamenities
     */
    propertyAmenities?: Array<PropertyOffersHotelAmenity> | null;
    /**
     * Pointofinterest
     */
    pointOfInterest?: Array<OfferPointOfInterest> | null;
    /**
     * Marketingmessage
     */
    marketingMessage?: string | null;
    /**
     * Currencycode
     */
    currencyCode?: string | null;
    /**
     * Primarylanguage
     */
    primaryLanguage?: string | null;
    /**
     * Totalnumberofrooms
     */
    totalNumberOfRooms?: number | null;
    /**
     * Petpolicy
     */
    petPolicy?: string | null;
};

/**
 * ContentRoomAmenity
 *
 * Room amenity information.
 */
export type ContentRoomAmenity = {
    /**
     * Roomamenity
     */
    roomAmenity: string;
    /**
     * Description
     */
    description: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Includeinrate
     */
    includeInRate: boolean;
    /**
     * Confirmable
     */
    confirmable: boolean;
};

/**
 * ContentRoomType
 *
 * Room type information.
 */
export type ContentRoomType = {
    /**
     * Hotelroomtype
     */
    hotelRoomType: string | null;
    /**
     * Roomtype
     */
    roomType: string | null;
    /**
     * Description
     */
    description?: Array<string>;
    /**
     * Roomname
     */
    roomName: string | null;
    /**
     * Roomcategory
     */
    roomCategory: string | null;
    /**
     * Roomamenities
     */
    roomAmenities?: Array<ContentRoomAmenity>;
    /**
     * Roomviewtype
     */
    roomViewType: string | null;
    /**
     * Roomprimarybedtype
     */
    roomPrimaryBedType: string | null;
    /**
     * Nonsmokingind
     */
    nonSmokingInd: boolean | null;
    occupancy?: Occupancy | null;
    /**
     * Numberofunits
     */
    numberOfUnits?: number | null;
};

/**
 * CreateReservationRequest
 *
 * Request to create a reservation.
 */
export type CreateReservationRequest = {
    /**
     * Reservations
     */
    reservations: {
        [key: string]: Array<ReservationInput>;
    };
};

/**
 * Description
 *
 * Description text.
 */
export type Description = {
    /**
     * Text
     */
    text?: string | null;
};

/**
 * Direction
 *
 * Directions to property.
 */
export type Direction = {
    /**
     * Propertydirection
     */
    propertyDirection?: string | null;
};

/**
 * DistributionReservationSummaryType
 *
 * Detailed statistics item for distribution summary.
 */
export type DistributionReservationSummaryType = {
    /**
     * Hotelid
     */
    hotelId?: string | null;
    /**
     * Channelcode
     */
    channelCode?: string | null;
    /**
     * Enterpriseid
     */
    enterpriseId?: string | null;
    /**
     * Arrivaldate
     */
    arrivalDate?: string | null;
    /**
     * Departuredate
     */
    departureDate?: string | null;
    /**
     * Creationdate
     */
    creationDate?: string | null;
    /**
     * Lastupdatedate
     */
    lastUpdateDate?: string | null;
    /**
     * Cancellationdate
     */
    cancellationDate?: string | null;
    /**
     * Numberofrooms
     */
    numberOfRooms?: number | null;
    /**
     * Reservationstatus
     */
    reservationStatus?: string | null;
    /**
     * Confirmationid
     */
    confirmationId?: string | null;
    /**
     * Legnumber
     */
    legNumber?: string | null;
    /**
     * Reservationid
     */
    reservationId?: string | null;
    /**
     * Guestname
     */
    guestName?: string | null;
    /**
     * Creatorid
     */
    creatorId?: string | null;
};

/**
 * DummyModelDTO
 *
 * DTO for dummy models.
 *
 * It returned when accessing dummy models from the API.
 */
export type DummyModelDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * DummyModelInputDTO
 *
 * DTO for creating new dummy model.
 */
export type DummyModelInputDto = {
    /**
     * Name
     */
    name: string;
};

/**
 * GeneralInformation
 *
 * General property information.
 */
export type GeneralInformation = {
    /**
     * Checkintime
     */
    checkInTime?: string | null;
    /**
     * Checkouttime
     */
    checkOutTime?: string | null;
};

/**
 * Guarantee
 *
 * Reservation guarantee info.
 */
export type Guarantee = {
    /**
     * Guaranteecode
     */
    guaranteeCode?: string | null;
    /**
     * Shortdescription
     */
    shortDescription?: string | null;
};

/**
 * GuestCounts
 *
 * Guest counts.
 */
export type GuestCounts = {
    /**
     * Adults
     */
    adults?: number | null;
    /**
     * Children
     */
    children?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HotelAvailabilityStatus
 *
 * Availability status of a hotel.
 */
export type HotelAvailabilityStatus = 'AvailableForSale' | 'NoAvailability' | 'NotFound' | 'OtherAvailable';

/**
 * Location
 *
 * Geographic location.
 */
export type Location = {
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
};

/**
 * Message
 *
 * Simple message model.
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NumericCategorySummaryType
 *
 * This element has count data for each count category.
 *
 * Such as number of guests, rooms occupied, etc.
 */
export type NumericCategorySummaryType = {
    /**
     * Value
     *
     * The total count for the category in NumericCategoryCode.
     */
    value?: number | null;
    /**
     * Code
     *
     * The representation of a numeric category such as Guests : Number of guests, RoomsOcc : Rooms occupied.
     */
    code?: string | null;
};

/**
 * Occupancy
 *
 * Details on the occupancy of the room type.
 */
export type Occupancy = {
    /**
     * Minoccupancy
     */
    minOccupancy: number;
    /**
     * Maxoccupancy
     */
    maxOccupancy: number;
    /**
     * Maxadultoccupancy
     */
    maxAdultOccupancy: number;
    /**
     * Maxchildoccupancy
     */
    maxChildOccupancy: number;
};

/**
 * Offer
 *
 * Offer details.
 */
export type Offer = {
    /**
     * Bookingcode
     */
    bookingCode?: string | null;
    /**
     * Offername
     */
    offerName?: string | null;
    /**
     * Availabilitystatus
     */
    availabilityStatus?: string | null;
    /**
     * Roomtype
     */
    roomType?: string | null;
    /**
     * Rateplancode
     */
    ratePlanCode?: string | null;
    /**
     * Ratechangeduringstay
     */
    rateChangeDuringStay?: boolean | null;
    rateInformation?: OfferRateInformation | null;
    /**
     * Packages
     */
    packages?: Array<RatePackage> | null;
    total?: OfferTotalTypeWithTaxes | null;
    /**
     * Blockinformation
     */
    blockInformation?: {
        [key: string]: unknown;
    } | null;
};

/**
 * OfferDetailsPropertyInfo
 *
 * Detailed property info for an offer.
 */
export type OfferDetailsPropertyInfo = {
    /**
     * Hotelcode
     */
    hotelCode?: string | null;
    /**
     * Hotelname
     */
    hotelName?: string | null;
    /**
     * Chaincode
     */
    chainCode?: string | null;
    /**
     * Isalternate
     */
    isAlternate?: boolean | null;
    address?: Address | null;
    /**
     * Propertyamenities
     */
    propertyAmenities?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Distance
     */
    distance?: {
        [key: string]: unknown;
    } | null;
    generalInformation?: GeneralInformation | null;
    communications?: Communications | null;
    /**
     * Transportations
     */
    transportations?: Array<Transportation> | null;
    direction?: Direction | null;
    location?: Location | null;
};

/**
 * OfferDetailsRatePlan
 *
 * Detailed rate plan for an offer.
 */
export type OfferDetailsRatePlan = {
    /**
     * Rateplancode
     */
    ratePlanCode?: string | null;
    /**
     * Rateplanname
     */
    ratePlanName?: string | null;
    /**
     * Rateplantype
     */
    ratePlanType?: string | null;
    /**
     * Accesscode
     */
    accessCode?: string | null;
    /**
     * Identificationrequired
     */
    identificationRequired?: boolean | null;
    /**
     * Accountid
     */
    accountId?: string | null;
    /**
     * Rateplanlevel
     */
    ratePlanLevel?: string | null;
    /**
     * Rateplancategory
     */
    ratePlanCategory?: string | null;
    gdsDescription?: Description | null;
    /**
     * Commissionable
     */
    commissionable?: boolean | null;
    /**
     * Commissiondescription
     */
    commissionDescription?: string | null;
    commission?: OfferRatePlanCommission | null;
    /**
     * Packages
     */
    packages?: Array<RatePackage> | null;
    mealPlan?: OfferMealPlan | null;
    /**
     * Promotioncodes
     */
    promotionCodes?: Array<PromotionCodeItem> | null;
};

/**
 * OfferDetailsResponse
 *
 * Response for a single offer detail.
 */
export type OfferDetailsResponse = {
    propertyInfo?: OfferDetailsPropertyInfo | null;
    availability?: HotelAvailabilityStatus | null;
    roomType?: OfferDetailsRoomType | null;
    ratePlan?: OfferDetailsRatePlan | null;
    offer?: Offer | null;
};

/**
 * OfferDetailsRoomType
 *
 * Detailed room type for an offer.
 */
export type OfferDetailsRoomType = {
    /**
     * Roomtypecode
     */
    roomTypeCode?: string | null;
    /**
     * Roomtypename
     */
    roomTypeName?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Availabilitystatus
     */
    availabilityStatus?: string | null;
};

/**
 * OfferMealPlan
 *
 * Meal plan details.
 */
export type OfferMealPlan = {
    /**
     * Code
     */
    code?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * OfferMinMaxTotalType
 *
 * Rate range information.
 */
export type OfferMinMaxTotalType = {
    /**
     * Amountbeforetax
     */
    amountBeforeTax?: number | null;
    /**
     * Amountaftertax
     */
    amountAfterTax?: number | null;
    /**
     * Currencycode
     */
    currencyCode?: string | null;
    rateMode?: OfferRateMode | null;
    /**
     * Iscommissionable
     */
    isCommissionable?: boolean | null;
    /**
     * Hasratechange
     */
    hasRateChange?: boolean | null;
};

/**
 * OfferOverallRateInformation
 *
 * Rate plan information of the offer.
 */
export type OfferOverallRateInformation = {
    rateModeAmount?: OfferTotalType | null;
    rateMode?: OfferRateMode | null;
};

/**
 * OfferPointOfInterest
 *
 * Point of interest information.
 */
export type OfferPointOfInterest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Distance
     */
    distance?: number | null;
    /**
     * Unit
     */
    unit?: string | null;
};

/**
 * OfferRateInformation
 *
 * Details on the rate plan of the offer.
 */
export type OfferRateInformation = {
    rate?: OfferOverallRateInformation | null;
    /**
     * Cancellationpolicies
     */
    cancellationPolicies?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Guaranteerequirement
     */
    guaranteeRequirement?: string | null;
    /**
     * Depositpolicies
     */
    depositPolicies?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * OfferRateMode
 *
 * Rate mode details.
 */
export type OfferRateMode = {
    /**
     * Type
     */
    type?: string | null;
};

/**
 * OfferRatePlanCommission
 *
 * Commission info for a rate plan.
 */
export type OfferRatePlanCommission = {
    /**
     * Percent
     */
    percent?: number | null;
    /**
     * Amount
     */
    amount?: number | null;
    /**
     * Currencycode
     */
    currencyCode?: string | null;
};

/**
 * OfferTotalType
 *
 * The daily rate of the offer.
 */
export type OfferTotalType = {
    /**
     * Amountbeforetax
     */
    amountBeforeTax?: number | null;
    /**
     * Amountaftertax
     */
    amountAfterTax?: number | null;
    /**
     * Currencycode
     */
    currencyCode?: string | null;
};

/**
 * OfferTotalTypeWithTaxes
 *
 * Total cost including taxes.
 */
export type OfferTotalTypeWithTaxes = {
    /**
     * Amountbeforetax
     */
    amountBeforeTax?: number | null;
    /**
     * Amountaftertax
     */
    amountAfterTax?: number | null;
    /**
     * Currencycode
     */
    currencyCode?: string | null;
};

/**
 * Profile
 *
 * Guest profile definition.
 */
export type Profile = {
    /**
     * Customer
     */
    customer?: {
        [key: string]: unknown;
    } | null;
    /**
     * Profiletype
     */
    profileType?: string | null;
};

/**
 * ProfileInfo
 *
 * Profile info containing profile details.
 */
export type ProfileInfo = {
    /**
     * Profileidlist
     */
    profileIdList?: Array<UniqueId> | null;
    profile?: Profile | null;
};

/**
 * PromotionCodeItem
 *
 * Promotion code item.
 */
export type PromotionCodeItem = {
    /**
     * Code
     */
    code?: string | null;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * PropertyInfoResponse
 *
 * Response for property information.
 */
export type PropertyInfoResponse = {
    propertyInfo?: ContentPropertyInfo | null;
};

/**
 * PropertyInfoSummaryResponse
 *
 * Response for property info summary.
 */
export type PropertyInfoSummaryResponse = {
    /**
     * Hasmore
     */
    hasMore?: boolean;
    /**
     * Totalresults
     */
    totalResults?: number | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Count
     */
    count?: number;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Hotels
     */
    hotels?: Array<PropertySnippet>;
};

/**
 * PropertyOffersHotelAmenity
 *
 * Hotel amenity information.
 */
export type PropertyOffersHotelAmenity = {
    /**
     * Code
     */
    code?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * PropertyOffersPropertyInfo
 *
 * Property info for offers, extends search info.
 */
export type PropertyOffersPropertyInfo = {
    /**
     * Hotelcode
     */
    hotelCode?: string | null;
    /**
     * Hotelname
     */
    hotelName?: string | null;
    /**
     * Chaincode
     */
    chainCode?: string | null;
    /**
     * Isalternate
     */
    isAlternate?: boolean | null;
    address?: Address | null;
    /**
     * Propertyamenities
     */
    propertyAmenities?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Distance
     */
    distance?: {
        [key: string]: unknown;
    } | null;
};

/**
 * PropertyOffersRatePlan
 *
 * Rate plan details for offers. Combines SearchRatePlan and more.
 */
export type PropertyOffersRatePlan = {
    /**
     * Rateplancode
     */
    ratePlanCode?: string | null;
    /**
     * Rateplanname
     */
    ratePlanName?: string | null;
    /**
     * Rateplantype
     */
    ratePlanType?: string | null;
    /**
     * Accesscode
     */
    accessCode?: string | null;
    /**
     * Identificationrequired
     */
    identificationRequired?: boolean | null;
    /**
     * Accountid
     */
    accountId?: string | null;
    /**
     * Rateplanlevel
     */
    ratePlanLevel?: string | null;
    /**
     * Rateplancategory
     */
    ratePlanCategory?: string | null;
    gdsDescription?: Description | null;
    /**
     * Commissionable
     */
    commissionable?: boolean | null;
    /**
     * Commissiondescription
     */
    commissionDescription?: string | null;
    commission?: OfferRatePlanCommission | null;
    /**
     * Packages
     */
    packages?: Array<RatePackage> | null;
    mealPlan?: OfferMealPlan | null;
    /**
     * Promotioncodes
     */
    promotionCodes?: Array<PromotionCodeItem> | null;
};

/**
 * PropertyOffersResponse
 *
 * Response for property offers search.
 */
export type PropertyOffersResponse = {
    /**
     * Roomstays
     */
    roomStays?: Array<PropertyOffersRoomStay> | null;
};

/**
 * PropertyOffersRoomStay
 *
 * Room stay details for property offers.
 */
export type PropertyOffersRoomStay = {
    propertyInfo?: PropertyOffersPropertyInfo | null;
    availability?: HotelAvailabilityStatus | null;
    /**
     * Restrictions
     */
    restrictions?: Array<Restriction> | null;
    /**
     * Roomtypes
     */
    roomTypes?: Array<PropertyOffersRoomType> | null;
    /**
     * Rateplans
     */
    ratePlans?: Array<PropertyOffersRatePlan> | null;
    /**
     * Offers
     */
    offers?: Array<Offer> | null;
};

/**
 * PropertyOffersRoomType
 *
 * Room type details for offers.
 */
export type PropertyOffersRoomType = {
    /**
     * Roomtypecode
     */
    roomTypeCode?: string | null;
    /**
     * Roomtypename
     */
    roomTypeName?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Availabilitystatus
     */
    availabilityStatus?: string | null;
};

/**
 * PropertySearchPropertyInfo
 *
 * Property info for search results.
 */
export type PropertySearchPropertyInfo = {
    /**
     * Hotelcode
     */
    hotelCode?: string | null;
    /**
     * Hotelname
     */
    hotelName?: string | null;
    /**
     * Chaincode
     */
    chainCode?: string | null;
    /**
     * Isalternate
     */
    isAlternate?: boolean | null;
};

/**
 * PropertySearchRatePlan
 *
 * Rate plan in search results.
 */
export type PropertySearchRatePlan = {
    /**
     * Rateplancode
     */
    ratePlanCode?: string | null;
    /**
     * Rateplanname
     */
    ratePlanName?: string | null;
    /**
     * Rateplantype
     */
    ratePlanType?: string | null;
    /**
     * Identificationrequired
     */
    identificationRequired?: boolean | null;
    /**
     * Accountid
     */
    accountId?: string | null;
    /**
     * Availabilitystatus
     */
    availabilityStatus?: string | null;
    /**
     * Additionaldetails
     */
    additionalDetails?: {
        [key: string]: unknown;
    } | null;
};

/**
 * PropertySearchResponse
 *
 * Response for property search.
 */
export type PropertySearchResponse = {
    /**
     * Roomstays
     */
    roomStays?: Array<PropertySearchRoomStay> | null;
};

/**
 * PropertySearchRoomStay
 *
 * Room stay details for property search.
 */
export type PropertySearchRoomStay = {
    propertyInfo?: PropertySearchPropertyInfo | null;
    availability?: HotelAvailabilityStatus | null;
    /**
     * Rateplans
     */
    ratePlans?: Array<PropertySearchRatePlan> | null;
    minRate?: OfferMinMaxTotalType | null;
    maxRate?: OfferMinMaxTotalType | null;
};

/**
 * PropertySnippet
 *
 * Snippet information for property summary.
 */
export type PropertySnippet = {
    /**
     * Hotelid
     */
    hotelId: string;
    /**
     * Hotelcode
     */
    hotelCode: string;
    /**
     * Hotelname
     */
    hotelName?: string | null;
    /**
     * Hoteldescription
     */
    hotelDescription?: string | null;
    address?: Operaclone2WebApiContentSchemaAddress;
    /**
     * Coordinates
     */
    coordinates?: {
        [key: string]: number;
    };
    /**
     * Connectivity
     */
    connectivity?: {
        [key: string]: string;
    };
    /**
     * Meta
     */
    meta?: {
        [key: string]: unknown;
    };
};

/**
 * Rate
 *
 * Daily rate info.
 */
export type Rate = {
    base?: RateTotal | null;
    total?: RateTotal | null;
    /**
     * Start
     */
    start?: string | null;
    /**
     * End
     */
    end?: string | null;
};

/**
 * RatePackage
 *
 * Package associated with a rate.
 */
export type RatePackage = {
    /**
     * Code
     */
    code?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * RateTotal
 *
 * Rate total definition.
 */
export type RateTotal = {
    /**
     * Amountbeforetax
     */
    amountBeforeTax?: number | null;
    /**
     * Amountaftertax
     */
    amountAfterTax?: number | null;
    /**
     * Currencycode
     */
    currencyCode?: string | null;
};

/**
 * Reservation
 *
 * Reservation model.
 */
export type ReservationInput = {
    /**
     * Reservationidlist
     */
    reservationIdList?: Array<UniqueId> | null;
    roomStay?: RoomStayInput | null;
    /**
     * Reservationguests
     */
    reservationGuests?: Array<ReservationGuestInput> | null;
    /**
     * Hotelid
     */
    hotelId?: string | null;
    /**
     * Reservationstatus
     */
    reservationStatus?: string | null;
    /**
     * Createdatetime
     */
    createDateTime?: string | null;
};

/**
 * Reservation
 *
 * Reservation model.
 */
export type ReservationOutput = {
    /**
     * Reservationidlist
     */
    reservationIdList?: Array<UniqueId> | null;
    roomStay?: RoomStayOutput | null;
    /**
     * Reservationguests
     */
    reservationGuests?: Array<ReservationGuestOutput> | null;
    /**
     * Hotelid
     */
    hotelId?: string | null;
    /**
     * Reservationstatus
     */
    reservationStatus?: string | null;
    /**
     * Createdatetime
     */
    createDateTime?: string | null;
};

/**
 * ReservationGuest
 *
 * Guest associated with a reservation.
 */
export type ReservationGuestInput = {
    profileInfo?: ProfileInfo | null;
    /**
     * Primary
     */
    primary?: boolean | null;
};

/**
 * ReservationGuest
 *
 * Guest associated with a reservation.
 */
export type ReservationGuestOutput = {
    profileInfo?: ProfileInfo | null;
    /**
     * Primary
     */
    primary?: boolean | null;
};

/**
 * ReservationListResponse
 *
 * Response containing a list of reservations.
 */
export type ReservationListResponse = {
    /**
     * Reservations
     */
    reservations?: {
        [key: string]: Array<ReservationOutput>;
    } | null;
};

/**
 * ReservationSummary
 *
 * Simplified reservation summary.
 */
export type ReservationSummary = {
    /**
     * Reservationid
     */
    reservationId?: string | null;
    /**
     * Confirmationnumber
     */
    confirmationNumber?: string | null;
    /**
     * Guestname
     */
    guestName?: string | null;
    /**
     * Arrivaldate
     */
    arrivalDate?: string | null;
    /**
     * Departuredate
     */
    departureDate?: string | null;
    /**
     * Status
     */
    status?: string | null;
};

/**
 * ReservationSummaryResponse
 *
 * Response containing a list of reservation summaries.
 */
export type ReservationSummaryResponse = {
    /**
     * Reservations
     */
    reservations?: Array<ReservationSummary> | null;
};

/**
 * Restriction
 *
 * Booking restriction.
 */
export type Restriction = {
    /**
     * Code
     */
    code?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * RevenueCategorySummaryType
 *
 * This element has revenue amount data for its revenue category.
 *
 * Such as Room Revenue, Food and Beverage Revenue.
 */
export type RevenueCategorySummaryType = {
    /**
     * Code
     *
     * The representation of a revenue category.
     */
    code?: string | null;
    /**
     * Amount
     *
     * A monetary amount.
     */
    amount?: number | null;
    /**
     * Currencycode
     *
     * Provides a currency code to reflect the currency in which an amount may be expressed.
     */
    currencyCode?: string | null;
};

/**
 * RoomRate
 *
 * Room rate details.
 */
export type RoomRateInput = {
    total?: RateTotal | null;
    /**
     * Rates
     */
    rates?: {
        [key: string]: Array<Rate>;
    } | null;
    /**
     * Roomtype
     */
    roomType?: string | null;
    /**
     * Rateplancode
     */
    ratePlanCode?: string | null;
    /**
     * Start
     */
    start?: string | null;
    /**
     * End
     */
    end?: string | null;
    guestCounts?: GuestCounts | null;
};

/**
 * RoomRate
 *
 * Room rate details.
 */
export type RoomRateOutput = {
    total?: RateTotal | null;
    /**
     * Rates
     */
    rates?: {
        [key: string]: Array<Rate>;
    } | null;
    /**
     * Roomtype
     */
    roomType?: string | null;
    /**
     * Rateplancode
     */
    ratePlanCode?: string | null;
    /**
     * Start
     */
    start?: string | null;
    /**
     * End
     */
    end?: string | null;
    guestCounts?: GuestCounts | null;
};

/**
 * RoomStay
 *
 * Room stay details.
 */
export type RoomStayInput = {
    /**
     * Arrivaldate
     */
    arrivalDate?: string | null;
    /**
     * Departuredate
     */
    departureDate?: string | null;
    guarantee?: Guarantee | null;
    /**
     * Roomrates
     */
    roomRates?: Array<RoomRateInput> | null;
    guestCounts?: GuestCounts | null;
};

/**
 * RoomStay
 *
 * Room stay details.
 */
export type RoomStayOutput = {
    /**
     * Arrivaldate
     */
    arrivalDate?: string | null;
    /**
     * Departuredate
     */
    departureDate?: string | null;
    guarantee?: Guarantee | null;
    /**
     * Roomrates
     */
    roomRates?: Array<RoomRateOutput> | null;
    guestCounts?: GuestCounts | null;
};

/**
 * RoomTypesResponse
 *
 * Response for room types information.
 */
export type RoomTypesResponse = {
    /**
     * Roomtypes
     */
    roomTypes?: Array<ContentRoomType> | null;
    /**
     * Count
     */
    count?: number | null;
    /**
     * Hasmore
     */
    hasMore?: boolean | null;
    /**
     * Limit
     */
    limit?: number | null;
    /**
     * Offset
     */
    offset?: number | null;
    /**
     * Totalresults
     */
    totalResults?: number | null;
};

/**
 * StatisticCodeType
 *
 * Defines the codes and corresponding categories.
 *
 * Data in the other elements has been gathered for these.
 */
export type StatisticCodeType = {
    /**
     * Statisticdate
     *
     * Collection of statistic summary data.
     */
    statisticDate?: Array<StatisticSetType> | null;
    /**
     * Statcode
     *
     * Actual code used by the system to collect the statistics (e.g. CORP, RACK if category is Market Segment).
     */
    statCode?: string | null;
    /**
     * Statcategorycode
     *
     * Category Code category of StatCode attribute (e.g. Market Segment).
     */
    statCategoryCode?: string | null;
    /**
     * Statcodeclass
     *
     * Class grouping of StatCode attribute.
     */
    statCodeClass?: string | null;
    /**
     * Description
     *
     * Statistic code description.
     */
    description?: string | null;
};

/**
 * StatisticSetType
 *
 * An instance of a statistic.
 *
 * It is a set containing revenue category and number category summaries.
 */
export type StatisticSetType = {
    /**
     * Revenue
     *
     * Collection of RevenueCategorySummary elements. Used if revenue values reported.
     */
    revenue?: Array<RevenueCategorySummaryType> | null;
    /**
     * Inventory
     *
     * Collection of CountCategorySummary elements. Used if count values reported.
     */
    inventory?: Array<NumericCategorySummaryType> | null;
    /**
     * Statisticdate
     *
     * Date of the statistic.
     */
    statisticDate?: string | null;
    /**
     * Weekenddate
     *
     * Determines whether statistic date is a weekend date.
     */
    weekendDate?: boolean | null;
};

/**
 * StatisticType
 *
 * Defines all details needed to create a statistical report.
 */
export type StatisticType = {
    /**
     * Statistics
     *
     * Statistic Codes.
     */
    statistics?: Array<StatisticCodeType> | null;
    /**
     * Hotelname
     *
     * A text field used to communicate the proper name of the hotel.
     */
    hotelName?: string | null;
    /**
     * Reportcode
     *
     * Identifies the type of statistics collected. Each ReportCode corresponds to a set of category summaries based upon a predetermined agreement.
     */
    reportCode?: string | null;
    /**
     * Description
     *
     * This element has revenue amount data for its revenue category such as Room Revenue, Food and Beverage Revenue.
     */
    description?: string | null;
};

/**
 * Transportation
 *
 * Transportation services.
 */
export type Transportation = {
    /**
     * Type
     */
    type?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * UniqueID
 *
 * Unique ID definition.
 */
export type UniqueId = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Type
     */
    type?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * Address
 *
 * Address information.
 */
export type Operaclone2WebApiContentSchemaAddress = {
    /**
     * Lines
     */
    lines?: Array<string> | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Postalcode
     */
    postalCode?: string | null;
    /**
     * Countrycode
     */
    countryCode?: string | null;
    /**
     * State
     */
    state?: string | null;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SendEchoMessageApiEchoPostData = {
    body: Message;
    path?: never;
    query?: never;
    url: '/api/echo/';
};

export type SendEchoMessageApiEchoPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendEchoMessageApiEchoPostError = SendEchoMessageApiEchoPostErrors[keyof SendEchoMessageApiEchoPostErrors];

export type SendEchoMessageApiEchoPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SendEchoMessageApiEchoPostResponse = SendEchoMessageApiEchoPostResponses[keyof SendEchoMessageApiEchoPostResponses];

export type GetDummyModelsApiDummyGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/dummy/';
};

export type GetDummyModelsApiDummyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDummyModelsApiDummyGetError = GetDummyModelsApiDummyGetErrors[keyof GetDummyModelsApiDummyGetErrors];

export type GetDummyModelsApiDummyGetResponses = {
    /**
     * Response Get Dummy Models Api Dummy  Get
     *
     * Successful Response
     */
    200: Array<DummyModelDto>;
};

export type GetDummyModelsApiDummyGetResponse = GetDummyModelsApiDummyGetResponses[keyof GetDummyModelsApiDummyGetResponses];

export type CreateDummyModelApiDummyPutData = {
    body: DummyModelInputDto;
    path?: never;
    query?: never;
    url: '/api/dummy/';
};

export type CreateDummyModelApiDummyPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDummyModelApiDummyPutError = CreateDummyModelApiDummyPutErrors[keyof CreateDummyModelApiDummyPutErrors];

export type CreateDummyModelApiDummyPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPropertiesApiShopV1HotelsGetData = {
    body?: never;
    headers: {
        /**
         * Authorization
         *
         * Bearer token
         */
        authorization?: string | null;
        /**
         * X-Channelcode
         *
         * Channel code
         */
        'x-channelCode': string;
        /**
         * X-App-Key
         *
         * Application Key
         */
        'x-app-key'?: string | null;
        /**
         * Accept-Language
         *
         * Language preference
         */
        'Accept-Language'?: string | null;
        /**
         * X-Request-Id
         *
         * Unique tracing key
         */
        'x-request-id'?: string | null;
        /**
         * X-Originating-Application
         *
         * Originating Application
         */
        'x-originating-application'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Hotelcodes
         *
         * List of Hotel Codes (CSV)
         */
        HotelCodes: string;
        /**
         * Arrivaldate
         *
         * Arrival/Check-in Date
         */
        ArrivalDate: string;
        /**
         * Arrivaldateto
         *
         * Arrival/Check-in Date To
         */
        ArrivalDateTo?: string | null;
        /**
         * Departuredate
         *
         * Departure/Check-out Date
         */
        DepartureDate: string;
        /**
         * Adults
         *
         * Number of adults
         */
        Adults?: number | null;
        /**
         * Children
         *
         * Number of children
         */
        Children?: number | null;
        /**
         * Childrenages
         *
         * List of Age of the children (CSV)
         */
        ChildrenAges?: string | null;
        /**
         * Rateplancodes
         *
         * List of Rate Plan codes (CSV)
         */
        RatePlanCodes?: string | null;
        /**
         * Accesscode
         *
         * Access code
         */
        AccessCode?: string | null;
        /**
         * Numberofunits
         *
         * Number of rooms
         */
        NumberOfUnits?: number | null;
        /**
         * Ratemode
         *
         * Rate mode
         */
        RateMode?: string | null;
        /**
         * Rateplancodematchonly
         */
        RatePlanCodeMatchOnly?: boolean | null;
        /**
         * Rateplantype
         *
         * Rate Plan type
         */
        RatePlanType?: string | null;
        /**
         * Availableonly
         */
        AvailableOnly?: boolean | null;
        /**
         * Minrate
         */
        minRate?: number | null;
        /**
         * Maxrate
         */
        maxRate?: number | null;
        /**
         * Alternateoffers
         */
        AlternateOffers?: string | null;
        /**
         * Commissionablestatus
         */
        CommissionableStatus?: string | null;
        /**
         * Promotioncodes
         *
         * List of Promotion codes (CSV)
         */
        PromotionCodes?: string | null;
    };
    url: '/api/shop/v1/hotels';
};

export type GetPropertiesApiShopV1HotelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropertiesApiShopV1HotelsGetError = GetPropertiesApiShopV1HotelsGetErrors[keyof GetPropertiesApiShopV1HotelsGetErrors];

export type GetPropertiesApiShopV1HotelsGetResponses = {
    /**
     * Successful Response
     */
    200: PropertySearchResponse;
};

export type GetPropertiesApiShopV1HotelsGetResponse = GetPropertiesApiShopV1HotelsGetResponses[keyof GetPropertiesApiShopV1HotelsGetResponses];

export type GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetData = {
    body?: never;
    headers: {
        /**
         * Authorization
         *
         * Bearer token
         */
        authorization?: string | null;
        /**
         * X-Channelcode
         *
         * Channel code
         */
        'x-channelCode': string;
        /**
         * X-App-Key
         *
         * Application Key
         */
        'x-app-key'?: string | null;
        /**
         * Accept-Language
         *
         * Language preference
         */
        'Accept-Language'?: string | null;
        /**
         * X-Request-Id
         *
         * Unique tracing key
         */
        'x-request-id'?: string | null;
        /**
         * X-Originating-Application
         */
        'x-originating-application'?: string | null;
    };
    path: {
        /**
         * Hotelcode
         *
         * Hotel Code
         */
        hotelCode: string;
    };
    query: {
        /**
         * Arrivaldate
         */
        ArrivalDate: string;
        /**
         * Departuredate
         */
        DepartureDate: string;
        /**
         * Adults
         */
        Adults?: number | null;
        /**
         * Children
         */
        Children?: number | null;
        /**
         * Childrenages
         */
        ChildrenAges?: string | null;
        /**
         * Roomtypes
         */
        RoomTypes?: string | null;
        /**
         * Rateplancodes
         */
        RatePlanCodes?: string | null;
        /**
         * Accesscode
         */
        AccessCode?: string | null;
        /**
         * Rateplantype
         */
        RatePlanType?: string | null;
        /**
         * Numberofunits
         */
        NumberOfUnits?: number | null;
        /**
         * Roomtypematchonly
         */
        RoomTypeMatchOnly?: boolean | null;
        /**
         * Rateplancodematchonly
         */
        RatePlanCodeMatchOnly?: boolean | null;
        /**
         * Ratemode
         */
        RateMode?: string | null;
        /**
         * Roomamenity
         */
        RoomAmenity?: string | null;
        /**
         * Roomamenityquantity
         */
        RoomAmenityQuantity?: number | null;
        /**
         * Includeamenities
         */
        IncludeAmenities?: boolean | null;
        /**
         * Minrate
         */
        minRate?: number | null;
        /**
         * Maxrate
         */
        maxRate?: number | null;
        /**
         * Alternateoffers
         */
        AlternateOffers?: string | null;
        /**
         * Commissionablestatus
         */
        CommissionableStatus?: string | null;
        /**
         * Promotioncodes
         */
        PromotionCodes?: string | null;
        /**
         * Blockcode
         */
        BlockCode?: string | null;
    };
    url: '/api/shop/v1/hotels/{hotelCode}/offers';
};

export type GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetError = GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetErrors[keyof GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetErrors];

export type GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetResponses = {
    /**
     * Successful Response
     */
    200: PropertyOffersResponse;
};

export type GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetResponse = GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetResponses[keyof GetPropertyOffersApiShopV1HotelsHotelCodeOffersGetResponses];

export type GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Externalsystem
         */
        'x-externalsystem'?: string | null;
        /**
         * X-App-Key
         */
        'x-app-key'?: string | null;
        /**
         * X-Channelcode
         */
        'x-channelCode'?: string | null;
        /**
         * Accept-Language
         */
        'Accept-Language'?: string | null;
        /**
         * X-Request-Id
         */
        'x-request-id'?: string | null;
        /**
         * X-Originating-Application
         */
        'x-originating-application'?: string | null;
    };
    path: {
        /**
         * Hotelcode
         */
        hotelCode: string;
    };
    query: {
        /**
         * Arrivaldate
         */
        ArrivalDate: string;
        /**
         * Departuredate
         */
        DepartureDate: string;
        /**
         * Adults
         */
        Adults?: number | null;
        /**
         * Children
         */
        Children?: number | null;
        /**
         * Childrenages
         */
        ChildrenAges?: string | null;
        /**
         * Roomtype
         */
        RoomType?: string | null;
        /**
         * Rateplancode
         */
        RatePlanCode?: string | null;
        /**
         * Accesscode
         */
        AccessCode?: string | null;
        /**
         * Ratemode
         */
        RateMode?: string | null;
        /**
         * Numberofunits
         */
        NumberOfUnits?: number | null;
        /**
         * Bookingcode
         */
        BookingCode?: string | null;
        /**
         * Includeamenities
         */
        IncludeAmenities?: boolean | null;
        /**
         * Promotioncodes
         */
        PromotionCodes?: string | null;
        /**
         * Blockcode
         */
        BlockCode?: string | null;
    };
    url: '/api/shop/v1/hotels/{hotelCode}/offer';
};

export type GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetError = GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetErrors[keyof GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetErrors];

export type GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetResponses = {
    /**
     * Successful Response
     */
    200: OfferDetailsResponse;
};

export type GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetResponse = GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetResponses[keyof GetPropertyOfferApiShopV1HotelsHotelCodeOfferGetResponses];

export type GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetData = {
    body?: never;
    path: {
        /**
         * Hotelid
         *
         * Unique ID of the hotel where inventory statistics are searched.
         */
        hotelId: string;
    };
    query: {
        /**
         * Daterangestart
         *
         * The starting value of the date range.
         */
        dateRangeStart: string;
        /**
         * Daterangeend
         *
         * The ending value of the date range.
         */
        dateRangeEnd: string;
        /**
         * Reportcode
         *
         * Identifies the type of statistics collected. Each ReportCode corresponds to a set of category summaries based upon a predetermined agreement.
         */
        reportCode: 'DetailedAvailabiltySummary' | 'RoomCalendarStatistics' | 'SellLimitSummary' | 'RoomsAvailabilitySummary';
        /**
         * Parametername
         *
         * Name of the parameter.
         */
        parameterName?: Array<string> | null;
        /**
         * Parametervalue
         *
         * Value of the parameter.
         */
        parameterValue?: Array<string> | null;
    };
    url: '/api/inv/v1/hotels/{hotelId}/inventoryStatistics';
};

export type GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetError = GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetErrors[keyof GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetErrors];

export type GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetResponses = {
    /**
     * Response Get Inventory Statistics Api Inv V1 Hotels  Hotelid  Inventorystatistics Get
     *
     * Successful Response
     */
    200: Array<StatisticType>;
};

export type GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetResponse = GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetResponses[keyof GetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetResponses];

export type GetPropertiesSummaryApiContentV1HotelsGetData = {
    body?: never;
    headers: {
        /**
         * Authorization
         *
         * Bearer token
         */
        authorization?: string | null;
        /**
         * X-Channelcode
         *
         * Channel code
         */
        'x-channelCode': string;
        /**
         * X-App-Key
         *
         * Application Key
         */
        'x-app-key'?: string | null;
        /**
         * X-Request-Id
         *
         * Unique tracing key
         */
        'x-request-id'?: string | null;
        /**
         * X-Originating-Application
         */
        'x-originating-application'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Connectionstatuslastchangedfrom
         */
        connectionStatusLastChangedFrom?: string | null;
        /**
         * Connectionstatuslastchangedto
         */
        connectionStatusLastChangedTo?: string | null;
        /**
         * Connectionstatus
         */
        connectionStatus?: string | null;
        /**
         * Fetchinstructions
         */
        fetchInstructions?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/content/v1/hotels';
};

export type GetPropertiesSummaryApiContentV1HotelsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropertiesSummaryApiContentV1HotelsGetError = GetPropertiesSummaryApiContentV1HotelsGetErrors[keyof GetPropertiesSummaryApiContentV1HotelsGetErrors];

export type GetPropertiesSummaryApiContentV1HotelsGetResponses = {
    /**
     * Successful Response
     */
    200: PropertyInfoSummaryResponse;
};

export type GetPropertiesSummaryApiContentV1HotelsGetResponse = GetPropertiesSummaryApiContentV1HotelsGetResponses[keyof GetPropertiesSummaryApiContentV1HotelsGetResponses];

export type GetPropertyInfoApiContentV1HotelsHotelCodeGetData = {
    body?: never;
    headers: {
        /**
         * Authorization
         *
         * Bearer token
         */
        authorization?: string | null;
        /**
         * X-Channelcode
         *
         * Channel code
         */
        'x-channelCode': string;
        /**
         * X-App-Key
         *
         * Application Key
         */
        'x-app-key'?: string | null;
        /**
         * X-Request-Id
         *
         * Unique tracing key
         */
        'x-request-id'?: string | null;
        /**
         * X-Originating-Application
         */
        'x-originating-application'?: string | null;
    };
    path: {
        /**
         * Hotelcode
         *
         * Hotel Code
         */
        hotelCode: string;
    };
    query?: never;
    url: '/api/content/v1/hotels/{hotelCode}';
};

export type GetPropertyInfoApiContentV1HotelsHotelCodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropertyInfoApiContentV1HotelsHotelCodeGetError = GetPropertyInfoApiContentV1HotelsHotelCodeGetErrors[keyof GetPropertyInfoApiContentV1HotelsHotelCodeGetErrors];

export type GetPropertyInfoApiContentV1HotelsHotelCodeGetResponses = {
    /**
     * Successful Response
     */
    200: PropertyInfoResponse;
};

export type GetPropertyInfoApiContentV1HotelsHotelCodeGetResponse = GetPropertyInfoApiContentV1HotelsHotelCodeGetResponses[keyof GetPropertyInfoApiContentV1HotelsHotelCodeGetResponses];

export type GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetData = {
    body?: never;
    headers: {
        /**
         * Authorization
         *
         * Bearer token
         */
        authorization?: string | null;
        /**
         * X-Channelcode
         *
         * Channel code
         */
        'x-channelCode': string;
        /**
         * X-App-Key
         *
         * Application Key
         */
        'x-app-key'?: string | null;
        /**
         * X-Request-Id
         *
         * Unique tracing key
         */
        'x-request-id'?: string | null;
        /**
         * X-Originating-Application
         */
        'x-originating-application'?: string | null;
    };
    path: {
        /**
         * Hotelcode
         *
         * Hotel Code
         */
        hotelCode: string;
    };
    query?: {
        /**
         * Includeroomamenities
         */
        includeRoomAmenities?: boolean | null;
        /**
         * Roomtype
         */
        roomType?: string | null;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
    };
    url: '/api/content/v1/hotels/{hotelCode}/roomTypes';
};

export type GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetError = GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetErrors[keyof GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetErrors];

export type GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetResponses = {
    /**
     * Successful Response
     */
    200: RoomTypesResponse;
};

export type GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetResponse = GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetResponses[keyof GetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetResponses];

export type GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetData = {
    body?: never;
    path: {
        /**
         * Hotelid
         */
        hotelId: string;
    };
    query?: {
        /**
         * Surname
         */
        surname?: string | null;
        /**
         * Givenname
         */
        givenName?: string | null;
        /**
         * Arrivalstartdate
         */
        arrivalStartDate?: string | null;
        /**
         * Arrivalenddate
         */
        arrivalEndDate?: string | null;
        /**
         * Confirmationnumberlist
         */
        confirmationNumberList?: Array<string> | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/rsv/v1/hotels/{hotelId}/reservations';
};

export type GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetError = GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetErrors[keyof GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetErrors];

export type GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetResponses = {
    /**
     * Successful Response
     */
    200: ReservationListResponse;
};

export type GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetResponse = GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetResponses[keyof GetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetResponses];

export type CreateReservationApiRsvV1HotelsHotelIdReservationsPostData = {
    body: CreateReservationRequest;
    path: {
        /**
         * Hotelid
         */
        hotelId: string;
    };
    query?: never;
    url: '/api/rsv/v1/hotels/{hotelId}/reservations';
};

export type CreateReservationApiRsvV1HotelsHotelIdReservationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReservationApiRsvV1HotelsHotelIdReservationsPostError = CreateReservationApiRsvV1HotelsHotelIdReservationsPostErrors[keyof CreateReservationApiRsvV1HotelsHotelIdReservationsPostErrors];

export type CreateReservationApiRsvV1HotelsHotelIdReservationsPostResponses = {
    /**
     * Successful Response
     */
    200: ReservationListResponse;
};

export type CreateReservationApiRsvV1HotelsHotelIdReservationsPostResponse = CreateReservationApiRsvV1HotelsHotelIdReservationsPostResponses[keyof CreateReservationApiRsvV1HotelsHotelIdReservationsPostResponses];

export type GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetData = {
    body?: never;
    path: {
        /**
         * Hotelid
         */
        hotelId: string;
    };
    query?: {
        /**
         * Arrivaldate
         */
        arrivalDate?: string | null;
        /**
         * Lastname
         */
        lastName?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/rsv/v1/hotels/{hotelId}/reservations/summary';
};

export type GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetError = GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetErrors[keyof GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetErrors];

export type GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: ReservationSummaryResponse;
};

export type GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetResponse = GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetResponses[keyof GetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetResponses];

export type GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetData = {
    body?: never;
    path: {
        /**
         * Hotelid
         */
        hotelId: string;
    };
    query?: {
        /**
         * Startdate
         */
        startDate?: string | null;
        /**
         * Enddate
         */
        endDate?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/rsv/v1/hotels/{hotelId}/reservations/statistics';
};

export type GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetError = GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetErrors[keyof GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetErrors];

export type GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetResponses = {
    /**
     * Successful Response
     */
    200: CheckDistributionReservationsSummary;
};

export type GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetResponse = GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetResponses[keyof GetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetResponses];

export type UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutData = {
    body: CreateReservationRequest;
    path: {
        /**
         * Hotelid
         */
        hotelId: string;
        /**
         * Reservationid
         */
        reservationId: string;
    };
    query?: never;
    url: '/api/rsv/v1/hotels/{hotelId}/reservations/{reservationId}';
};

export type UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutError = UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutErrors[keyof UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutErrors];

export type UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutResponses = {
    /**
     * Successful Response
     */
    200: ReservationListResponse;
};

export type UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutResponse = UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutResponses[keyof UpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutResponses];

export type CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostData = {
    body: CancelReservationRequest;
    path: {
        /**
         * Hotelid
         */
        hotelId: string;
        /**
         * Reservationid
         */
        reservationId: string;
    };
    query?: never;
    url: '/api/rsv/v1/hotels/{hotelId}/reservations/{reservationId}/cancellations';
};

export type CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostError = CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostErrors[keyof CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostErrors];

export type CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostResponses = {
    /**
     * Successful Response
     */
    201: CancelReservationDetails;
};

export type CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostResponse = CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostResponses[keyof CancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostResponses];
