// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * AdditionalDetails
 *
 * Additional information related to the rate plan.
 */
export const zAdditionalDetails = z.object({
    ratePlanMatches: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    value: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Address
 *
 * Address information.
 */
export const zAddress = z.object({
    addressLine: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    city: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    postalCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    countryCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    state: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    county: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * AlternatePropertyDistance
 *
 * Distance from the property to the alternate property.
 */
export const zAlternatePropertyDistance = z.object({
    distance: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    distanceUnit: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    compassDirection: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    comments: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * BlockInformation
 *
 * Block related information.
 */
export const zBlockInformation = z.object({
    blockCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    blockId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    blockName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * CancelReason
 *
 * Reason for cancellation.
 */
export const zCancelReason = z.object({
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    code: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Communications
 *
 * Property communication channels.
 */
export const zCommunications = z.object({
    phone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Connectivity
 *
 * Connectivity status information.
 */
export const zConnectivity = z.object({
    connectionStatus: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * ContentRoomAmenity
 *
 * Room amenity information.
 */
export const zContentRoomAmenity = z.object({
    roomAmenity: z.string(),
    description: z.string(),
    quantity: z.int(),
    includeInRate: z.boolean(),
    confirmable: z.boolean()
});

/**
 * Coordinates
 *
 * Geographic coordinates.
 */
export const zCoordinates = z.object({
    latitude: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    longitude: z.optional(z.union([
        z.number(),
        z.null()
    ]))
});

/**
 * Description
 *
 * Description text.
 */
export const zDescription = z.object({
    text: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Direction
 *
 * Directions to property.
 */
export const zDirection = z.object({
    propertyDirection: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * DistributionReservationSummaryType
 *
 * Detailed statistics item for distribution summary.
 */
export const zDistributionReservationSummaryType = z.object({
    hotelId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    channelCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    enterpriseId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    arrivalDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    departureDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    creationDate: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    lastUpdateDate: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    cancellationDate: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    numberOfRooms: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    reservationStatus: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    confirmationId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    legNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    reservationId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    guestName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    creatorId: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * CheckDistributionReservationsSummary
 *
 * Response wrapper for distribution statistics.
 */
export const zCheckDistributionReservationsSummary = z.object({
    checkReservations: z.optional(z.union([
        z.array(zDistributionReservationSummaryType),
        z.null()
    ])),
    hasMore: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

/**
 * DummyModelDTO
 *
 * DTO for dummy models.
 *
 * It returned when accessing dummy models from the API.
 */
export const zDummyModelDto = z.object({
    id: z.int(),
    name: z.string()
});

/**
 * DummyModelInputDTO
 *
 * DTO for creating new dummy model.
 */
export const zDummyModelInputDto = z.object({
    name: z.string()
});

/**
 * GeneralInformation
 *
 * General property information.
 */
export const zGeneralInformation = z.object({
    checkInTime: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    checkOutTime: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Guarantee
 *
 * Reservation guarantee info.
 */
export const zGuarantee = z.object({
    guaranteeCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    shortDescription: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * GuestCounts
 *
 * Guest counts.
 */
export const zGuestCounts = z.object({
    adults: z.optional(z.union([
        z.int(),
        z.null()
    ])).default(1),
    children: z.optional(z.union([
        z.int(),
        z.null()
    ])).default(0)
});

/**
 * HotelAvailabilityStatus
 *
 * Availability status of a hotel.
 */
export const zHotelAvailabilityStatus = z.enum([
    'AvailableForSale',
    'NoAvailability',
    'NotFound',
    'OtherAvailable'
]);

/**
 * Location
 *
 * Geographic location.
 */
export const zLocation = z.object({
    latitude: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    longitude: z.optional(z.union([
        z.number(),
        z.null()
    ]))
});

/**
 * Message
 *
 * Simple message model.
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * NumericCategorySummaryType
 *
 * This element has count data for each count category.
 *
 * Such as number of guests, rooms occupied, etc.
 */
export const zNumericCategorySummaryType = z.object({
    value: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    code: z.optional(z.union([
        z.string().max(40),
        z.null()
    ]))
});

/**
 * Occupancy
 *
 * Details on the occupancy of the room type.
 */
export const zOccupancy = z.object({
    minOccupancy: z.int(),
    maxOccupancy: z.int(),
    maxAdultOccupancy: z.int(),
    maxChildOccupancy: z.int()
});

/**
 * ContentRoomType
 *
 * Room type information.
 */
export const zContentRoomType = z.object({
    hotelRoomType: z.union([
        z.string(),
        z.null()
    ]),
    roomType: z.union([
        z.string(),
        z.null()
    ]),
    description: z.optional(z.array(z.string())).default([]),
    roomName: z.union([
        z.string(),
        z.null()
    ]),
    roomCategory: z.union([
        z.string(),
        z.null()
    ]),
    roomAmenities: z.optional(z.array(zContentRoomAmenity)).default([]),
    roomViewType: z.union([
        z.string(),
        z.null()
    ]),
    roomPrimaryBedType: z.union([
        z.string(),
        z.null()
    ]),
    nonSmokingInd: z.union([
        z.boolean(),
        z.null()
    ]),
    occupancy: z.optional(z.union([
        zOccupancy,
        z.null()
    ])),
    numberOfUnits: z.optional(z.union([
        z.int(),
        z.null()
    ]))
});

/**
 * OfferCancelPenalty
 *
 * Cancellation penalty details.
 */
export const zOfferCancelPenalty = z.object({
    deadline: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    amountPercent: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    penaltyDescription: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferDepositPolicy
 *
 * Deposit policy details.
 */
export const zOfferDepositPolicy = z.object({
    depositRequired: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    amountPercent: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    deadline: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    depositDescription: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferDetailsRoomType
 *
 * Detailed room type for an offer.
 */
export const zOfferDetailsRoomType = z.object({
    roomTypeCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    roomTypeName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    availabilityStatus: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferMealPlan
 *
 * Meal plan details.
 */
export const zOfferMealPlan = z.object({
    code: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferPointOfInterest
 *
 * Point of interest information.
 */
export const zOfferPointOfInterest = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    distance: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    unit: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferRateMode
 *
 * Rate mode details.
 */
export const zOfferRateMode = z.object({
    type: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferMinMaxTotalType
 *
 * Rate range information.
 */
export const zOfferMinMaxTotalType = z.object({
    amountBeforeTax: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    amountAfterTax: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    rateMode: z.optional(z.union([
        zOfferRateMode,
        z.null()
    ])),
    isCommissionable: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    hasRateChange: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

/**
 * OfferRatePlanCommission
 *
 * Commission info for a rate plan.
 */
export const zOfferRatePlanCommission = z.object({
    percent: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    amount: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferTotalType
 *
 * The daily rate of the offer.
 */
export const zOfferTotalType = z.object({
    amountBeforeTax: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    amountAfterTax: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferOverallRateInformation
 *
 * Rate plan information of the offer.
 */
export const zOfferOverallRateInformation = z.object({
    rateModeAmount: z.optional(z.union([
        zOfferTotalType,
        z.null()
    ])),
    rateMode: z.optional(z.union([
        zOfferRateMode,
        z.null()
    ]))
});

/**
 * OfferRateInformation
 *
 * Details on the rate plan of the offer.
 */
export const zOfferRateInformation = z.object({
    rate: z.optional(z.union([
        zOfferOverallRateInformation,
        z.null()
    ])),
    cancellationPolicies: z.optional(z.union([
        z.array(zOfferCancelPenalty),
        z.null()
    ])),
    guaranteeRequirement: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    depositPolicies: z.optional(z.union([
        z.array(zOfferDepositPolicy),
        z.null()
    ]))
});

/**
 * OfferTotalTypeWithTaxes
 *
 * Total cost including taxes.
 */
export const zOfferTotalTypeWithTaxes = z.object({
    amountBeforeTax: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    amountAfterTax: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PersonName
 *
 * Person name definition.
 */
export const zPersonName = z.object({
    givenName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    surname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    nameType: z.optional(z.union([
        z.string(),
        z.null()
    ])).default('Primary')
});

/**
 * Customer
 *
 * Customer information.
 */
export const zCustomer = z.object({
    personName: z.optional(z.union([
        z.array(zPersonName),
        z.null()
    ]))
});

/**
 * Profile
 *
 * Guest profile definition.
 */
export const zProfileInput = z.object({
    customer: z.optional(z.union([
        zCustomer,
        z.null()
    ])),
    profileType: z.optional(z.union([
        z.string(),
        z.null()
    ])).default('Guest')
});

/**
 * Profile
 *
 * Guest profile definition.
 */
export const zProfileOutput = z.object({
    customer: z.optional(z.union([
        zCustomer,
        z.null()
    ])),
    profileType: z.optional(z.union([
        z.string(),
        z.null()
    ])).default('Guest')
});

/**
 * PromotionCodeItem
 *
 * Promotion code item.
 */
export const zPromotionCodeItem = z.object({
    code: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PropertyOffersHotelAmenity
 *
 * Hotel amenity information.
 */
export const zPropertyOffersHotelAmenity = z.object({
    code: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PropertyOffersPropertyInfo
 *
 * Property info for offers, extends search info.
 */
export const zPropertyOffersPropertyInfo = z.object({
    hotelCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    hotelName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    chainCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isAlternate: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    address: z.optional(z.union([
        zAddress,
        z.null()
    ])),
    propertyAmenities: z.optional(z.union([
        z.array(zPropertyOffersHotelAmenity),
        z.null()
    ])),
    distance: z.optional(z.union([
        zAlternatePropertyDistance,
        z.null()
    ]))
});

/**
 * PropertyOffersRoomType
 *
 * Room type details for offers.
 */
export const zPropertyOffersRoomType = z.object({
    roomTypeCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    roomTypeName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    availabilityStatus: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PropertySearchPropertyInfo
 *
 * Property info for search results.
 */
export const zPropertySearchPropertyInfo = z.object({
    hotelCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    hotelName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    chainCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isAlternate: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

/**
 * PropertySearchRatePlan
 *
 * Rate plan in search results.
 */
export const zPropertySearchRatePlan = z.object({
    ratePlanCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    identificationRequired: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    accountId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    availabilityStatus: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    additionalDetails: z.optional(z.union([
        zAdditionalDetails,
        z.null()
    ]))
});

/**
 * PropertySearchRoomStay
 *
 * Room stay details for property search.
 */
export const zPropertySearchRoomStay = z.object({
    propertyInfo: z.optional(z.union([
        zPropertySearchPropertyInfo,
        z.null()
    ])),
    availability: z.optional(z.union([
        zHotelAvailabilityStatus,
        z.null()
    ])),
    ratePlans: z.optional(z.union([
        z.array(zPropertySearchRatePlan),
        z.null()
    ])),
    minRate: z.optional(z.union([
        zOfferMinMaxTotalType,
        z.null()
    ])),
    maxRate: z.optional(z.union([
        zOfferMinMaxTotalType,
        z.null()
    ]))
});

/**
 * PropertySearchResponse
 *
 * Response for property search.
 */
export const zPropertySearchResponse = z.object({
    roomStays: z.optional(z.union([
        z.array(zPropertySearchRoomStay),
        z.null()
    ]))
});

/**
 * RatePackage
 *
 * Package associated with a rate.
 */
export const zRatePackage = z.object({
    code: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Offer
 *
 * Offer details.
 */
export const zOffer = z.object({
    bookingCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    offerName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    availabilityStatus: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    roomType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    rateChangeDuringStay: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    rateInformation: z.optional(z.union([
        zOfferRateInformation,
        z.null()
    ])),
    packages: z.optional(z.union([
        z.array(zRatePackage),
        z.null()
    ])),
    total: z.optional(z.union([
        zOfferTotalTypeWithTaxes,
        z.null()
    ])),
    blockInformation: z.optional(z.union([
        zBlockInformation,
        z.null()
    ]))
});

/**
 * OfferDetailsRatePlan
 *
 * Detailed rate plan for an offer.
 */
export const zOfferDetailsRatePlan = z.object({
    ratePlanCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    accessCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    identificationRequired: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    accountId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanLevel: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanCategory: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    gdsDescription: z.optional(z.union([
        zDescription,
        z.null()
    ])),
    commissionable: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    commissionDescription: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    commission: z.optional(z.union([
        zOfferRatePlanCommission,
        z.null()
    ])),
    packages: z.optional(z.union([
        z.array(zRatePackage),
        z.null()
    ])),
    mealPlan: z.optional(z.union([
        zOfferMealPlan,
        z.null()
    ])),
    promotionCodes: z.optional(z.union([
        z.array(zPromotionCodeItem),
        z.null()
    ]))
});

/**
 * PropertyOffersRatePlan
 *
 * Rate plan details for offers. Combines SearchRatePlan and more.
 */
export const zPropertyOffersRatePlan = z.object({
    ratePlanCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    accessCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    identificationRequired: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    accountId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanLevel: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanCategory: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    gdsDescription: z.optional(z.union([
        zDescription,
        z.null()
    ])),
    commissionable: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    commissionDescription: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    commission: z.optional(z.union([
        zOfferRatePlanCommission,
        z.null()
    ])),
    packages: z.optional(z.union([
        z.array(zRatePackage),
        z.null()
    ])),
    mealPlan: z.optional(z.union([
        zOfferMealPlan,
        z.null()
    ])),
    promotionCodes: z.optional(z.union([
        z.array(zPromotionCodeItem),
        z.null()
    ]))
});

/**
 * RateTotal
 *
 * Rate total definition.
 */
export const zRateTotal = z.object({
    amountBeforeTax: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    amountAfterTax: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Rate
 *
 * Daily rate info.
 */
export const zRate = z.object({
    base: z.optional(z.union([
        zRateTotal,
        z.null()
    ])),
    total: z.optional(z.union([
        zRateTotal,
        z.null()
    ])),
    start: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    end: z.optional(z.union([
        z.iso.date(),
        z.null()
    ]))
});

/**
 * RatesByDate
 *
 * Daily rates organized by date.
 */
export const zRatesByDateInput = z.object({
    day: z.optional(z.union([
        z.array(zRate),
        z.null()
    ]))
});

/**
 * RatesByDate
 *
 * Daily rates organized by date.
 */
export const zRatesByDateOutput = z.object({
    day: z.optional(z.union([
        z.array(zRate),
        z.null()
    ]))
});

/**
 * ReservationSummary
 *
 * Simplified reservation summary.
 */
export const zReservationSummary = z.object({
    reservationId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    confirmationNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    guestName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    arrivalDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    departureDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    status: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * ReservationSummaryResponse
 *
 * Response containing a list of reservation summaries.
 */
export const zReservationSummaryResponse = z.object({
    reservations: z.optional(z.union([
        z.array(zReservationSummary),
        z.null()
    ]))
});

/**
 * Restriction
 *
 * Booking restriction.
 */
export const zRestriction = z.object({
    code: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PropertyOffersRoomStay
 *
 * Room stay details for property offers.
 */
export const zPropertyOffersRoomStay = z.object({
    propertyInfo: z.optional(z.union([
        zPropertyOffersPropertyInfo,
        z.null()
    ])),
    availability: z.optional(z.union([
        zHotelAvailabilityStatus,
        z.null()
    ])),
    restrictions: z.optional(z.union([
        z.array(zRestriction),
        z.null()
    ])),
    roomTypes: z.optional(z.union([
        z.array(zPropertyOffersRoomType),
        z.null()
    ])),
    ratePlans: z.optional(z.union([
        z.array(zPropertyOffersRatePlan),
        z.null()
    ])),
    offers: z.optional(z.union([
        z.array(zOffer),
        z.null()
    ]))
});

/**
 * PropertyOffersResponse
 *
 * Response for property offers search.
 */
export const zPropertyOffersResponse = z.object({
    roomStays: z.optional(z.union([
        z.array(zPropertyOffersRoomStay),
        z.null()
    ]))
});

/**
 * RevenueCategorySummaryType
 *
 * This element has revenue amount data for its revenue category.
 *
 * Such as Room Revenue, Food and Beverage Revenue.
 */
export const zRevenueCategorySummaryType = z.object({
    code: z.optional(z.union([
        z.string().max(40),
        z.null()
    ])),
    amount: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string().length(3),
        z.null()
    ]))
});

/**
 * RoomRate
 *
 * Room rate details.
 */
export const zRoomRateInput = z.object({
    total: z.optional(z.union([
        zRateTotal,
        z.null()
    ])),
    rates: z.optional(z.union([
        zRatesByDateInput,
        z.null()
    ])),
    roomType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    start: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    end: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    guestCounts: z.optional(z.union([
        zGuestCounts,
        z.null()
    ]))
});

/**
 * RoomRate
 *
 * Room rate details.
 */
export const zRoomRateOutput = z.object({
    total: z.optional(z.union([
        zRateTotal,
        z.null()
    ])),
    rates: z.optional(z.union([
        zRatesByDateOutput,
        z.null()
    ])),
    roomType: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ratePlanCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    start: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    end: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    guestCounts: z.optional(z.union([
        zGuestCounts,
        z.null()
    ]))
});

/**
 * RoomStay
 *
 * Room stay details.
 */
export const zRoomStayInput = z.object({
    arrivalDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    departureDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    guarantee: z.optional(z.union([
        zGuarantee,
        z.null()
    ])),
    roomRates: z.optional(z.union([
        z.array(zRoomRateInput),
        z.null()
    ])),
    guestCounts: z.optional(z.union([
        zGuestCounts,
        z.null()
    ]))
});

/**
 * RoomStay
 *
 * Room stay details.
 */
export const zRoomStayOutput = z.object({
    arrivalDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    departureDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    guarantee: z.optional(z.union([
        zGuarantee,
        z.null()
    ])),
    roomRates: z.optional(z.union([
        z.array(zRoomRateOutput),
        z.null()
    ])),
    guestCounts: z.optional(z.union([
        zGuestCounts,
        z.null()
    ]))
});

/**
 * RoomTypesResponse
 *
 * Response for room types information.
 */
export const zRoomTypesResponse = z.object({
    roomTypes: z.optional(z.union([
        z.array(zContentRoomType),
        z.null()
    ])),
    count: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    hasMore: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    limit: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    offset: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    totalResults: z.optional(z.union([
        z.int(),
        z.null()
    ]))
});

/**
 * StatisticSetType
 *
 * An instance of a statistic.
 *
 * It is a set containing revenue category and number category summaries.
 */
export const zStatisticSetType = z.object({
    revenue: z.optional(z.union([
        z.array(zRevenueCategorySummaryType).max(4000),
        z.null()
    ])),
    inventory: z.optional(z.union([
        z.array(zNumericCategorySummaryType).max(4000),
        z.null()
    ])),
    statisticDate: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    weekendDate: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

/**
 * StatisticCodeType
 *
 * Defines the codes and corresponding categories.
 *
 * Data in the other elements has been gathered for these.
 */
export const zStatisticCodeType = z.object({
    statisticDate: z.optional(z.union([
        z.array(zStatisticSetType).max(4000),
        z.null()
    ])),
    statCode: z.optional(z.union([
        z.string().max(20),
        z.null()
    ])),
    statCategoryCode: z.optional(z.union([
        z.string().max(40),
        z.null()
    ])),
    statCodeClass: z.optional(z.union([
        z.string().max(40),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string().max(2000),
        z.null()
    ]))
});

/**
 * StatisticType
 *
 * Defines all details needed to create a statistical report.
 */
export const zStatisticType = z.object({
    statistics: z.optional(z.union([
        z.array(zStatisticCodeType).max(4000),
        z.null()
    ])),
    hotelName: z.optional(z.union([
        z.string().max(80),
        z.null()
    ])),
    reportCode: z.optional(z.union([
        z.string().max(100),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string().max(2000),
        z.null()
    ]))
});

/**
 * Transportation
 *
 * Transportation services.
 */
export const zTransportation = z.object({
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * OfferDetailsPropertyInfo
 *
 * Detailed property info for an offer.
 */
export const zOfferDetailsPropertyInfo = z.object({
    hotelCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    hotelName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    chainCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    isAlternate: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    address: z.optional(z.union([
        zAddress,
        z.null()
    ])),
    propertyAmenities: z.optional(z.union([
        z.array(zPropertyOffersHotelAmenity),
        z.null()
    ])),
    distance: z.optional(z.union([
        zAlternatePropertyDistance,
        z.null()
    ])),
    generalInformation: z.optional(z.union([
        zGeneralInformation,
        z.null()
    ])),
    communications: z.optional(z.union([
        zCommunications,
        z.null()
    ])),
    transportations: z.optional(z.union([
        z.array(zTransportation),
        z.null()
    ])),
    direction: z.optional(z.union([
        zDirection,
        z.null()
    ])),
    location: z.optional(z.union([
        zLocation,
        z.null()
    ]))
});

/**
 * OfferDetailsResponse
 *
 * Response for a single offer detail.
 */
export const zOfferDetailsResponse = z.object({
    propertyInfo: z.optional(z.union([
        zOfferDetailsPropertyInfo,
        z.null()
    ])),
    availability: z.optional(z.union([
        zHotelAvailabilityStatus,
        z.null()
    ])),
    roomType: z.optional(z.union([
        zOfferDetailsRoomType,
        z.null()
    ])),
    ratePlan: z.optional(z.union([
        zOfferDetailsRatePlan,
        z.null()
    ])),
    offer: z.optional(z.union([
        zOffer,
        z.null()
    ]))
});

/**
 * UniqueID
 *
 * Unique ID definition.
 */
export const zUniqueId = z.object({
    id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * CancelReservationDetails
 *
 * Details of a canceled reservation.
 */
export const zCancelReservationDetails = z.object({
    reservationIdList: z.optional(z.union([
        z.array(zUniqueId),
        z.null()
    ])),
    cancellationNumber: z.optional(z.union([
        zUniqueId,
        z.null()
    ])),
    status: z.optional(z.union([
        z.string(),
        z.null()
    ])).default('Cancelled')
});

/**
 * ProfileInfo
 *
 * Profile info containing profile details.
 */
export const zProfileInfoInput = z.object({
    profileIdList: z.optional(z.union([
        z.array(zUniqueId),
        z.null()
    ])),
    profile: z.optional(z.union([
        zProfileInput,
        z.null()
    ]))
});

/**
 * ProfileInfo
 *
 * Profile info containing profile details.
 */
export const zProfileInfoOutput = z.object({
    profileIdList: z.optional(z.union([
        z.array(zUniqueId),
        z.null()
    ])),
    profile: z.optional(z.union([
        zProfileOutput,
        z.null()
    ]))
});

/**
 * ReservationCancellationItem
 *
 * Reservation item for cancellation.
 */
export const zReservationCancellationItem = z.object({
    reservationIdList: z.optional(z.union([
        z.array(zUniqueId),
        z.null()
    ])),
    hotelId: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * CancelReservationRequest
 *
 * Request to cancel a reservation.
 */
export const zCancelReservationRequest = z.object({
    reason: z.optional(z.union([
        zCancelReason,
        z.null()
    ])),
    reservations: z.optional(z.union([
        z.array(zReservationCancellationItem),
        z.null()
    ]))
});

/**
 * ReservationGuest
 *
 * Guest associated with a reservation.
 */
export const zReservationGuestInput = z.object({
    profileInfo: z.optional(z.union([
        zProfileInfoInput,
        z.null()
    ])),
    primary: z.optional(z.union([
        z.boolean(),
        z.null()
    ])).default(true)
});

/**
 * Reservation
 *
 * Reservation model.
 */
export const zReservationInput = z.object({
    reservationIdList: z.optional(z.union([
        z.array(zUniqueId),
        z.null()
    ])),
    roomStay: z.optional(z.union([
        zRoomStayInput,
        z.null()
    ])),
    reservationGuests: z.optional(z.union([
        z.array(zReservationGuestInput),
        z.null()
    ])),
    hotelId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    reservationStatus: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    createDateTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

/**
 * ReservationCollection
 *
 * Collection wrapper for reservations.
 */
export const zReservationCollectionInput = z.object({
    reservation: z.optional(z.union([
        z.array(zReservationInput),
        z.null()
    ]))
});

/**
 * CreateReservationRequest
 *
 * Request to create a reservation.
 */
export const zCreateReservationRequest = z.object({
    reservations: zReservationCollectionInput
});

/**
 * ReservationGuest
 *
 * Guest associated with a reservation.
 */
export const zReservationGuestOutput = z.object({
    profileInfo: z.optional(z.union([
        zProfileInfoOutput,
        z.null()
    ])),
    primary: z.optional(z.union([
        z.boolean(),
        z.null()
    ])).default(true)
});

/**
 * Reservation
 *
 * Reservation model.
 */
export const zReservationOutput = z.object({
    reservationIdList: z.optional(z.union([
        z.array(zUniqueId),
        z.null()
    ])),
    roomStay: z.optional(z.union([
        zRoomStayOutput,
        z.null()
    ])),
    reservationGuests: z.optional(z.union([
        z.array(zReservationGuestOutput),
        z.null()
    ])),
    hotelId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    reservationStatus: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    createDateTime: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ]))
});

/**
 * ReservationCollection
 *
 * Collection wrapper for reservations.
 */
export const zReservationCollectionOutput = z.object({
    reservation: z.optional(z.union([
        z.array(zReservationOutput),
        z.null()
    ]))
});

/**
 * ReservationListResponse
 *
 * Response containing a list of reservations.
 */
export const zReservationListResponse = z.object({
    reservations: z.optional(z.union([
        zReservationCollectionOutput,
        z.null()
    ]))
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

/**
 * Address
 *
 * Address information.
 */
export const zOperaclone2WebApiContentSchemaAddress = z.object({
    lines: z.optional(z.union([
        z.array(z.string()),
        z.null()
    ])),
    city: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    postalCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    countryCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    state: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * ContentPropertyInfo
 *
 * Property information details.
 */
export const zContentPropertyInfo = z.object({
    hotelId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    enterpriseId: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    hotelCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    hotelName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    hotelDescription: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    chainCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    clusterCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    address: z.optional(z.union([
        zOperaclone2WebApiContentSchemaAddress,
        z.null()
    ])),
    latitude: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    longitude: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    propertyAmenities: z.optional(z.union([
        z.array(zPropertyOffersHotelAmenity),
        z.null()
    ])),
    pointOfInterest: z.optional(z.union([
        z.array(zOfferPointOfInterest),
        z.null()
    ])),
    marketingMessage: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    currencyCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    primaryLanguage: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    totalNumberOfRooms: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    petPolicy: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * PropertyInfoResponse
 *
 * Response for property information.
 */
export const zPropertyInfoResponse = z.object({
    propertyInfo: z.optional(z.union([
        zContentPropertyInfo,
        z.null()
    ]))
});

/**
 * PropertySnippet
 *
 * Snippet information for property summary.
 */
export const zPropertySnippet = z.object({
    hotelId: z.string(),
    hotelCode: z.string(),
    hotelName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    hotelDescription: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    address: z.optional(zOperaclone2WebApiContentSchemaAddress).default({}),
    coordinates: z.optional(zCoordinates).default({}),
    connectivity: z.optional(zConnectivity).default({}),
    meta: z.optional(z.record(z.string(), z.unknown())).default({})
});

/**
 * PropertyInfoSummaryResponse
 *
 * Response for property info summary.
 */
export const zPropertyInfoSummaryResponse = z.object({
    hasMore: z.optional(z.boolean()).default(true),
    totalResults: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    limit: z.optional(z.int()).default(20),
    count: z.optional(z.int()).default(20),
    offset: z.optional(z.int()).default(0),
    hotels: z.optional(z.array(zPropertySnippet)).default([])
});

export const zHealthCheckApiHealthGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zSendEchoMessageApiEchoPostData = z.object({
    body: zMessage,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zSendEchoMessageApiEchoPostResponse = zMessage;

export const zGetDummyModelsApiDummyGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        limit: z.optional(z.int()).default(10),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Response Get Dummy Models Api Dummy  Get
 *
 * Successful Response
 */
export const zGetDummyModelsApiDummyGetResponse = z.array(zDummyModelDto);

export const zCreateDummyModelApiDummyPutData = z.object({
    body: zDummyModelInputDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetPropertiesApiShopV1HotelsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        HotelCodes: z.string(),
        ArrivalDate: z.iso.date(),
        ArrivalDateTo: z.optional(z.union([
            z.iso.date(),
            z.null()
        ])),
        DepartureDate: z.iso.date(),
        Adults: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(1),
        Children: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(0),
        ChildrenAges: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RatePlanCodes: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        AccessCode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        NumberOfUnits: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(1),
        RateMode: z.optional(z.union([
            z.string(),
            z.null()
        ])).default('Highest'),
        RatePlanCodeMatchOnly: z.optional(z.union([
            z.boolean(),
            z.null()
        ])).default(false),
        RatePlanType: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        AvailableOnly: z.optional(z.union([
            z.boolean(),
            z.null()
        ])).default(false),
        minRate: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        maxRate: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        AlternateOffers: z.optional(z.union([
            z.string(),
            z.null()
        ])).default('Always'),
        CommissionableStatus: z.optional(z.union([
            z.string(),
            z.null()
        ])).default('Both'),
        PromotionCodes: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }),
    headers: z.object({
        authorization: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-channelCode': z.string(),
        'x-app-key': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'Accept-Language': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-request-id': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-originating-application': z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })
});

/**
 * Successful Response
 */
export const zGetPropertiesApiShopV1HotelsGetResponse = zPropertySearchResponse;

export const zGetPropertyOffersApiShopV1HotelsHotelCodeOffersGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.object({
        ArrivalDate: z.iso.date(),
        DepartureDate: z.iso.date(),
        Adults: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(1),
        Children: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(0),
        ChildrenAges: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RoomTypes: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RatePlanCodes: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        AccessCode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RatePlanType: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        NumberOfUnits: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        RoomTypeMatchOnly: z.optional(z.union([
            z.boolean(),
            z.null()
        ])),
        RatePlanCodeMatchOnly: z.optional(z.union([
            z.boolean(),
            z.null()
        ])),
        RateMode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RoomAmenity: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RoomAmenityQuantity: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        IncludeAmenities: z.optional(z.union([
            z.boolean(),
            z.null()
        ])),
        minRate: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        maxRate: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        AlternateOffers: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        CommissionableStatus: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        PromotionCodes: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        BlockCode: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }),
    headers: z.object({
        authorization: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-channelCode': z.string(),
        'x-app-key': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'Accept-Language': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-request-id': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-originating-application': z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })
});

/**
 * Successful Response
 */
export const zGetPropertyOffersApiShopV1HotelsHotelCodeOffersGetResponse = zPropertyOffersResponse;

export const zGetPropertyOfferApiShopV1HotelsHotelCodeOfferGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.object({
        ArrivalDate: z.iso.date(),
        DepartureDate: z.iso.date(),
        Adults: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(1),
        Children: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(0),
        ChildrenAges: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RoomType: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RatePlanCode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        AccessCode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        RateMode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        NumberOfUnits: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        BookingCode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        IncludeAmenities: z.optional(z.union([
            z.boolean(),
            z.null()
        ])),
        PromotionCodes: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        BlockCode: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }),
    headers: z.optional(z.object({
        authorization: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-externalsystem': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-app-key': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-channelCode': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'Accept-Language': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-request-id': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-originating-application': z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }))
});

/**
 * Successful Response
 */
export const zGetPropertyOfferApiShopV1HotelsHotelCodeOfferGetResponse = zOfferDetailsResponse;

export const zGetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelId: z.string().min(1).max(2000)
    }),
    query: z.object({
        dateRangeStart: z.iso.date(),
        dateRangeEnd: z.iso.date(),
        reportCode: z.enum([
            'DetailedAvailabiltySummary',
            'RoomCalendarStatistics',
            'SellLimitSummary',
            'RoomsAvailabilitySummary'
        ]),
        parameterName: z.optional(z.union([
            z.array(z.string()),
            z.null()
        ])),
        parameterValue: z.optional(z.union([
            z.array(z.string()),
            z.null()
        ]))
    })
});

/**
 * Response Get Inventory Statistics Api Inv V1 Hotels  Hotelid  Inventorystatistics Get
 *
 * Successful Response
 */
export const zGetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetResponse = z.array(zStatisticType);

export const zGetPropertiesSummaryApiContentV1HotelsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        connectionStatusLastChangedFrom: z.optional(z.union([
            z.iso.datetime(),
            z.null()
        ])),
        connectionStatusLastChangedTo: z.optional(z.union([
            z.iso.datetime(),
            z.null()
        ])),
        connectionStatus: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        fetchInstructions: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        limit: z.optional(z.int()).default(20),
        offset: z.optional(z.int()).default(0)
    })),
    headers: z.object({
        authorization: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-channelCode': z.string(),
        'x-app-key': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-request-id': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-originating-application': z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })
});

/**
 * Successful Response
 */
export const zGetPropertiesSummaryApiContentV1HotelsGetResponse = zPropertyInfoSummaryResponse;

export const zGetPropertyInfoApiContentV1HotelsHotelCodeGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.object({
        authorization: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-channelCode': z.string(),
        'x-app-key': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-request-id': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-originating-application': z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })
});

/**
 * Successful Response
 */
export const zGetPropertyInfoApiContentV1HotelsHotelCodeGetResponse = zPropertyInfoResponse;

export const zGetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.optional(z.object({
        includeRoomAmenities: z.optional(z.union([
            z.boolean(),
            z.null()
        ])).default(false),
        roomType: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        limit: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(20),
        offset: z.optional(z.union([
            z.int(),
            z.null()
        ])).default(0)
    })),
    headers: z.object({
        authorization: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-channelCode': z.string(),
        'x-app-key': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-request-id': z.optional(z.union([
            z.string(),
            z.null()
        ])),
        'x-originating-application': z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })
});

/**
 * Successful Response
 */
export const zGetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetResponse = zRoomTypesResponse;

export const zGetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.optional(z.object({
        surname: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        givenName: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        arrivalStartDate: z.optional(z.union([
            z.iso.date(),
            z.null()
        ])),
        arrivalEndDate: z.optional(z.union([
            z.iso.date(),
            z.null()
        ])),
        confirmationNumberList: z.optional(z.union([
            z.array(z.string()),
            z.null()
        ])),
        limit: z.optional(z.int()).default(100),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Successful Response
 */
export const zGetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetResponse = zReservationListResponse;

export const zCreateReservationApiRsvV1HotelsHotelIdReservationsPostData = z.object({
    body: zCreateReservationRequest,
    path: z.object({
        hotelId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zCreateReservationApiRsvV1HotelsHotelIdReservationsPostResponse = zReservationListResponse;

export const zGetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.optional(z.object({
        arrivalDate: z.optional(z.union([
            z.iso.date(),
            z.null()
        ])),
        lastName: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        limit: z.optional(z.int()).default(200),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Successful Response
 */
export const zGetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetResponse = zReservationSummaryResponse;

export const zGetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.optional(z.object({
        startDate: z.optional(z.union([
            z.iso.date(),
            z.null()
        ])),
        endDate: z.optional(z.union([
            z.iso.date(),
            z.null()
        ])),
        limit: z.optional(z.int()).default(20),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Successful Response
 */
export const zGetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetResponse = zCheckDistributionReservationsSummary;

export const zUpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutData = z.object({
    body: zCreateReservationRequest,
    path: z.object({
        hotelId: z.string(),
        reservationId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zUpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutResponse = zReservationListResponse;

export const zCancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostData = z.object({
    body: zCancelReservationRequest,
    path: z.object({
        hotelId: z.string(),
        reservationId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zCancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostResponse = zCancelReservationDetails;
