// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Address
 *
 * Address information.
 */
export const zAddress = z.object({
    addressLine: z.union([
        z.array(z.string()),
        z.null()
    ]).optional(),
    city: z.union([
        z.string(),
        z.null()
    ]).optional(),
    postalCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    countryCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    state: z.union([
        z.string(),
        z.null()
    ]).optional(),
    county: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * CancelReason
 *
 * Reason for cancellation.
 */
export const zCancelReason = z.object({
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    code: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * CancelReservationRequest
 *
 * Request to cancel a reservation.
 */
export const zCancelReservationRequest = z.object({
    reason: z.union([
        zCancelReason,
        z.null()
    ]).optional(),
    reservations: z.union([
        z.array(z.record(z.unknown())),
        z.null()
    ]).optional()
});

/**
 * Communications
 *
 * Property communication channels.
 */
export const zCommunications = z.object({
    phone: z.union([
        z.string(),
        z.null()
    ]).optional(),
    email: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * ContentRoomAmenity
 *
 * Room amenity information.
 */
export const zContentRoomAmenity = z.object({
    roomAmenity: z.string(),
    description: z.string(),
    quantity: z.number().int(),
    includeInRate: z.boolean(),
    confirmable: z.boolean()
});

/**
 * Description
 *
 * Description text.
 */
export const zDescription = z.object({
    text: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Direction
 *
 * Directions to property.
 */
export const zDirection = z.object({
    propertyDirection: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * DistributionReservationSummaryType
 *
 * Detailed statistics item for distribution summary.
 */
export const zDistributionReservationSummaryType = z.object({
    hotelId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    channelCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    enterpriseId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    arrivalDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    departureDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    creationDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    lastUpdateDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    cancellationDate: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    numberOfRooms: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    reservationStatus: z.union([
        z.string(),
        z.null()
    ]).optional(),
    confirmationId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    legNumber: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reservationId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    guestName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    creatorId: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * CheckDistributionReservationsSummary
 *
 * Response wrapper for distribution statistics.
 */
export const zCheckDistributionReservationsSummary = z.object({
    checkReservations: z.union([
        z.array(zDistributionReservationSummaryType),
        z.null()
    ]).optional(),
    hasMore: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

/**
 * DummyModelDTO
 *
 * DTO for dummy models.
 *
 * It returned when accessing dummy models from the API.
 */
export const zDummyModelDto = z.object({
    id: z.number().int(),
    name: z.string()
});

/**
 * DummyModelInputDTO
 *
 * DTO for creating new dummy model.
 */
export const zDummyModelInputDto = z.object({
    name: z.string()
});

/**
 * GeneralInformation
 *
 * General property information.
 */
export const zGeneralInformation = z.object({
    checkInTime: z.union([
        z.string(),
        z.null()
    ]).optional(),
    checkOutTime: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Guarantee
 *
 * Reservation guarantee info.
 */
export const zGuarantee = z.object({
    guaranteeCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    shortDescription: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * GuestCounts
 *
 * Guest counts.
 */
export const zGuestCounts = z.object({
    adults: z.union([
        z.number().int(),
        z.null()
    ]).optional().default(1),
    children: z.union([
        z.number().int(),
        z.null()
    ]).optional().default(0)
});

/**
 * HotelAvailabilityStatus
 *
 * Availability status of a hotel.
 */
export const zHotelAvailabilityStatus = z.enum([
    'AvailableForSale',
    'NoAvailability',
    'NotFound',
    'OtherAvailable'
]);

/**
 * Location
 *
 * Geographic location.
 */
export const zLocation = z.object({
    latitude: z.union([
        z.number(),
        z.null()
    ]).optional(),
    longitude: z.union([
        z.number(),
        z.null()
    ]).optional()
});

/**
 * Message
 *
 * Simple message model.
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * NumericCategorySummaryType
 *
 * This element has count data for each count category.
 *
 * Such as number of guests, rooms occupied, etc.
 */
export const zNumericCategorySummaryType = z.object({
    value: z.union([
        z.number(),
        z.null()
    ]).optional(),
    code: z.union([
        z.string().max(40),
        z.null()
    ]).optional()
});

/**
 * Occupancy
 *
 * Details on the occupancy of the room type.
 */
export const zOccupancy = z.object({
    minOccupancy: z.number().int(),
    maxOccupancy: z.number().int(),
    maxAdultOccupancy: z.number().int(),
    maxChildOccupancy: z.number().int()
});

/**
 * ContentRoomType
 *
 * Room type information.
 */
export const zContentRoomType = z.object({
    hotelRoomType: z.union([
        z.string(),
        z.null()
    ]),
    roomType: z.union([
        z.string(),
        z.null()
    ]),
    description: z.array(z.string()).optional().default([]),
    roomName: z.union([
        z.string(),
        z.null()
    ]),
    roomCategory: z.union([
        z.string(),
        z.null()
    ]),
    roomAmenities: z.array(zContentRoomAmenity).optional().default([]),
    roomViewType: z.union([
        z.string(),
        z.null()
    ]),
    roomPrimaryBedType: z.union([
        z.string(),
        z.null()
    ]),
    nonSmokingInd: z.union([
        z.boolean(),
        z.null()
    ]),
    occupancy: z.union([
        zOccupancy,
        z.null()
    ]).optional(),
    numberOfUnits: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * OfferDetailsRoomType
 *
 * Detailed room type for an offer.
 */
export const zOfferDetailsRoomType = z.object({
    roomTypeCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    roomTypeName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    availabilityStatus: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * OfferMealPlan
 *
 * Meal plan details.
 */
export const zOfferMealPlan = z.object({
    code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * OfferPointOfInterest
 *
 * Point of interest information.
 */
export const zOfferPointOfInterest = z.object({
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    distance: z.union([
        z.number(),
        z.null()
    ]).optional(),
    unit: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * OfferRateMode
 *
 * Rate mode details.
 */
export const zOfferRateMode = z.object({
    type: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * OfferMinMaxTotalType
 *
 * Rate range information.
 */
export const zOfferMinMaxTotalType = z.object({
    amountBeforeTax: z.union([
        z.number(),
        z.null()
    ]).optional(),
    amountAfterTax: z.union([
        z.number(),
        z.null()
    ]).optional(),
    currencyCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    rateMode: z.union([
        zOfferRateMode,
        z.null()
    ]).optional(),
    isCommissionable: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    hasRateChange: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

/**
 * OfferRatePlanCommission
 *
 * Commission info for a rate plan.
 */
export const zOfferRatePlanCommission = z.object({
    percent: z.union([
        z.number(),
        z.null()
    ]).optional(),
    amount: z.union([
        z.number(),
        z.null()
    ]).optional(),
    currencyCode: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * OfferTotalType
 *
 * The daily rate of the offer.
 */
export const zOfferTotalType = z.object({
    amountBeforeTax: z.union([
        z.number(),
        z.null()
    ]).optional(),
    amountAfterTax: z.union([
        z.number(),
        z.null()
    ]).optional(),
    currencyCode: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * OfferOverallRateInformation
 *
 * Rate plan information of the offer.
 */
export const zOfferOverallRateInformation = z.object({
    rateModeAmount: z.union([
        zOfferTotalType,
        z.null()
    ]).optional(),
    rateMode: z.union([
        zOfferRateMode,
        z.null()
    ]).optional()
});

/**
 * OfferRateInformation
 *
 * Details on the rate plan of the offer.
 */
export const zOfferRateInformation = z.object({
    rate: z.union([
        zOfferOverallRateInformation,
        z.null()
    ]).optional(),
    cancellationPolicies: z.union([
        z.array(z.record(z.unknown())),
        z.null()
    ]).optional(),
    guaranteeRequirement: z.union([
        z.string(),
        z.null()
    ]).optional(),
    depositPolicies: z.union([
        z.array(z.record(z.unknown())),
        z.null()
    ]).optional()
});

/**
 * OfferTotalTypeWithTaxes
 *
 * Total cost including taxes.
 */
export const zOfferTotalTypeWithTaxes = z.object({
    amountBeforeTax: z.union([
        z.number(),
        z.null()
    ]).optional(),
    amountAfterTax: z.union([
        z.number(),
        z.null()
    ]).optional(),
    currencyCode: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Profile
 *
 * Guest profile definition.
 */
export const zProfile = z.object({
    customer: z.union([
        z.record(z.unknown()),
        z.null()
    ]).optional(),
    profileType: z.union([
        z.string(),
        z.null()
    ]).optional().default('Guest')
});

/**
 * PromotionCodeItem
 *
 * Promotion code item.
 */
export const zPromotionCodeItem = z.object({
    code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * PropertyOffersHotelAmenity
 *
 * Hotel amenity information.
 */
export const zPropertyOffersHotelAmenity = z.object({
    code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * PropertyOffersPropertyInfo
 *
 * Property info for offers, extends search info.
 */
export const zPropertyOffersPropertyInfo = z.object({
    hotelCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    hotelName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    chainCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    isAlternate: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    address: z.union([
        zAddress,
        z.null()
    ]).optional(),
    propertyAmenities: z.union([
        z.array(z.record(z.unknown())),
        z.null()
    ]).optional(),
    distance: z.union([
        z.record(z.unknown()),
        z.null()
    ]).optional()
});

/**
 * PropertyOffersRoomType
 *
 * Room type details for offers.
 */
export const zPropertyOffersRoomType = z.object({
    roomTypeCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    roomTypeName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    availabilityStatus: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * PropertySearchPropertyInfo
 *
 * Property info for search results.
 */
export const zPropertySearchPropertyInfo = z.object({
    hotelCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    hotelName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    chainCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    isAlternate: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

/**
 * PropertySearchRatePlan
 *
 * Rate plan in search results.
 */
export const zPropertySearchRatePlan = z.object({
    ratePlanCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanType: z.union([
        z.string(),
        z.null()
    ]).optional(),
    identificationRequired: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    accountId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    availabilityStatus: z.union([
        z.string(),
        z.null()
    ]).optional(),
    additionalDetails: z.union([
        z.record(z.unknown()),
        z.null()
    ]).optional()
});

/**
 * PropertySearchRoomStay
 *
 * Room stay details for property search.
 */
export const zPropertySearchRoomStay = z.object({
    propertyInfo: z.union([
        zPropertySearchPropertyInfo,
        z.null()
    ]).optional(),
    availability: z.union([
        zHotelAvailabilityStatus,
        z.null()
    ]).optional(),
    ratePlans: z.union([
        z.array(zPropertySearchRatePlan),
        z.null()
    ]).optional(),
    minRate: z.union([
        zOfferMinMaxTotalType,
        z.null()
    ]).optional(),
    maxRate: z.union([
        zOfferMinMaxTotalType,
        z.null()
    ]).optional()
});

/**
 * PropertySearchResponse
 *
 * Response for property search.
 */
export const zPropertySearchResponse = z.object({
    roomStays: z.union([
        z.array(zPropertySearchRoomStay),
        z.null()
    ]).optional()
});

/**
 * RatePackage
 *
 * Package associated with a rate.
 */
export const zRatePackage = z.object({
    code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Offer
 *
 * Offer details.
 */
export const zOffer = z.object({
    bookingCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    offerName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    availabilityStatus: z.union([
        z.string(),
        z.null()
    ]).optional(),
    roomType: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    rateChangeDuringStay: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    rateInformation: z.union([
        zOfferRateInformation,
        z.null()
    ]).optional(),
    packages: z.union([
        z.array(zRatePackage),
        z.null()
    ]).optional(),
    total: z.union([
        zOfferTotalTypeWithTaxes,
        z.null()
    ]).optional(),
    blockInformation: z.union([
        z.record(z.unknown()),
        z.null()
    ]).optional()
});

/**
 * OfferDetailsRatePlan
 *
 * Detailed rate plan for an offer.
 */
export const zOfferDetailsRatePlan = z.object({
    ratePlanCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanType: z.union([
        z.string(),
        z.null()
    ]).optional(),
    accessCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    identificationRequired: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    accountId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanLevel: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanCategory: z.union([
        z.string(),
        z.null()
    ]).optional(),
    gdsDescription: z.union([
        zDescription,
        z.null()
    ]).optional(),
    commissionable: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    commissionDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    commission: z.union([
        zOfferRatePlanCommission,
        z.null()
    ]).optional(),
    packages: z.union([
        z.array(zRatePackage),
        z.null()
    ]).optional(),
    mealPlan: z.union([
        zOfferMealPlan,
        z.null()
    ]).optional(),
    promotionCodes: z.union([
        z.array(zPromotionCodeItem),
        z.null()
    ]).optional()
});

/**
 * PropertyOffersRatePlan
 *
 * Rate plan details for offers. Combines SearchRatePlan and more.
 */
export const zPropertyOffersRatePlan = z.object({
    ratePlanCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanType: z.union([
        z.string(),
        z.null()
    ]).optional(),
    accessCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    identificationRequired: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    accountId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanLevel: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanCategory: z.union([
        z.string(),
        z.null()
    ]).optional(),
    gdsDescription: z.union([
        zDescription,
        z.null()
    ]).optional(),
    commissionable: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    commissionDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    commission: z.union([
        zOfferRatePlanCommission,
        z.null()
    ]).optional(),
    packages: z.union([
        z.array(zRatePackage),
        z.null()
    ]).optional(),
    mealPlan: z.union([
        zOfferMealPlan,
        z.null()
    ]).optional(),
    promotionCodes: z.union([
        z.array(zPromotionCodeItem),
        z.null()
    ]).optional()
});

/**
 * RateTotal
 *
 * Rate total definition.
 */
export const zRateTotal = z.object({
    amountBeforeTax: z.union([
        z.number(),
        z.null()
    ]).optional(),
    amountAfterTax: z.union([
        z.number(),
        z.null()
    ]).optional(),
    currencyCode: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Rate
 *
 * Daily rate info.
 */
export const zRate = z.object({
    base: z.union([
        zRateTotal,
        z.null()
    ]).optional(),
    total: z.union([
        zRateTotal,
        z.null()
    ]).optional(),
    start: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    end: z.union([
        z.string().date(),
        z.null()
    ]).optional()
});

/**
 * ReservationSummary
 *
 * Simplified reservation summary.
 */
export const zReservationSummary = z.object({
    reservationId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    confirmationNumber: z.union([
        z.string(),
        z.null()
    ]).optional(),
    guestName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    arrivalDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    departureDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    status: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * ReservationSummaryResponse
 *
 * Response containing a list of reservation summaries.
 */
export const zReservationSummaryResponse = z.object({
    reservations: z.union([
        z.array(zReservationSummary),
        z.null()
    ]).optional()
});

/**
 * Restriction
 *
 * Booking restriction.
 */
export const zRestriction = z.object({
    code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * PropertyOffersRoomStay
 *
 * Room stay details for property offers.
 */
export const zPropertyOffersRoomStay = z.object({
    propertyInfo: z.union([
        zPropertyOffersPropertyInfo,
        z.null()
    ]).optional(),
    availability: z.union([
        zHotelAvailabilityStatus,
        z.null()
    ]).optional(),
    restrictions: z.union([
        z.array(zRestriction),
        z.null()
    ]).optional(),
    roomTypes: z.union([
        z.array(zPropertyOffersRoomType),
        z.null()
    ]).optional(),
    ratePlans: z.union([
        z.array(zPropertyOffersRatePlan),
        z.null()
    ]).optional(),
    offers: z.union([
        z.array(zOffer),
        z.null()
    ]).optional()
});

/**
 * PropertyOffersResponse
 *
 * Response for property offers search.
 */
export const zPropertyOffersResponse = z.object({
    roomStays: z.union([
        z.array(zPropertyOffersRoomStay),
        z.null()
    ]).optional()
});

/**
 * RevenueCategorySummaryType
 *
 * This element has revenue amount data for its revenue category.
 *
 * Such as Room Revenue, Food and Beverage Revenue.
 */
export const zRevenueCategorySummaryType = z.object({
    code: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    amount: z.union([
        z.number(),
        z.null()
    ]).optional(),
    currencyCode: z.union([
        z.string().length(3),
        z.null()
    ]).optional()
});

/**
 * RoomRate
 *
 * Room rate details.
 */
export const zRoomRateInput = z.object({
    total: z.union([
        zRateTotal,
        z.null()
    ]).optional(),
    rates: z.union([
        z.record(z.array(zRate)),
        z.null()
    ]).optional(),
    roomType: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    start: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    end: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    guestCounts: z.union([
        zGuestCounts,
        z.null()
    ]).optional()
});

/**
 * RoomRate
 *
 * Room rate details.
 */
export const zRoomRateOutput = z.object({
    total: z.union([
        zRateTotal,
        z.null()
    ]).optional(),
    rates: z.union([
        z.record(z.array(zRate)),
        z.null()
    ]).optional(),
    roomType: z.union([
        z.string(),
        z.null()
    ]).optional(),
    ratePlanCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    start: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    end: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    guestCounts: z.union([
        zGuestCounts,
        z.null()
    ]).optional()
});

/**
 * RoomStay
 *
 * Room stay details.
 */
export const zRoomStayInput = z.object({
    arrivalDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    departureDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    guarantee: z.union([
        zGuarantee,
        z.null()
    ]).optional(),
    roomRates: z.union([
        z.array(zRoomRateInput),
        z.null()
    ]).optional(),
    guestCounts: z.union([
        zGuestCounts,
        z.null()
    ]).optional()
});

/**
 * RoomStay
 *
 * Room stay details.
 */
export const zRoomStayOutput = z.object({
    arrivalDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    departureDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    guarantee: z.union([
        zGuarantee,
        z.null()
    ]).optional(),
    roomRates: z.union([
        z.array(zRoomRateOutput),
        z.null()
    ]).optional(),
    guestCounts: z.union([
        zGuestCounts,
        z.null()
    ]).optional()
});

/**
 * RoomTypesResponse
 *
 * Response for room types information.
 */
export const zRoomTypesResponse = z.object({
    roomTypes: z.union([
        z.array(zContentRoomType),
        z.null()
    ]).optional(),
    count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    hasMore: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    limit: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    offset: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    totalResults: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * StatisticSetType
 *
 * An instance of a statistic.
 *
 * It is a set containing revenue category and number category summaries.
 */
export const zStatisticSetType = z.object({
    revenue: z.union([
        z.array(zRevenueCategorySummaryType).max(4000),
        z.null()
    ]).optional(),
    inventory: z.union([
        z.array(zNumericCategorySummaryType).max(4000),
        z.null()
    ]).optional(),
    statisticDate: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    weekendDate: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

/**
 * StatisticCodeType
 *
 * Defines the codes and corresponding categories.
 *
 * Data in the other elements has been gathered for these.
 */
export const zStatisticCodeType = z.object({
    statisticDate: z.union([
        z.array(zStatisticSetType).max(4000),
        z.null()
    ]).optional(),
    statCode: z.union([
        z.string().max(20),
        z.null()
    ]).optional(),
    statCategoryCode: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    statCodeClass: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    description: z.union([
        z.string().max(2000),
        z.null()
    ]).optional()
});

/**
 * StatisticType
 *
 * Defines all details needed to create a statistical report.
 */
export const zStatisticType = z.object({
    statistics: z.union([
        z.array(zStatisticCodeType).max(4000),
        z.null()
    ]).optional(),
    hotelName: z.union([
        z.string().max(80),
        z.null()
    ]).optional(),
    reportCode: z.union([
        z.string().max(100),
        z.null()
    ]).optional(),
    description: z.union([
        z.string().max(2000),
        z.null()
    ]).optional()
});

/**
 * Transportation
 *
 * Transportation services.
 */
export const zTransportation = z.object({
    type: z.union([
        z.string(),
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * OfferDetailsPropertyInfo
 *
 * Detailed property info for an offer.
 */
export const zOfferDetailsPropertyInfo = z.object({
    hotelCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    hotelName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    chainCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    isAlternate: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    address: z.union([
        zAddress,
        z.null()
    ]).optional(),
    propertyAmenities: z.union([
        z.array(z.record(z.unknown())),
        z.null()
    ]).optional(),
    distance: z.union([
        z.record(z.unknown()),
        z.null()
    ]).optional(),
    generalInformation: z.union([
        zGeneralInformation,
        z.null()
    ]).optional(),
    communications: z.union([
        zCommunications,
        z.null()
    ]).optional(),
    transportations: z.union([
        z.array(zTransportation),
        z.null()
    ]).optional(),
    direction: z.union([
        zDirection,
        z.null()
    ]).optional(),
    location: z.union([
        zLocation,
        z.null()
    ]).optional()
});

/**
 * OfferDetailsResponse
 *
 * Response for a single offer detail.
 */
export const zOfferDetailsResponse = z.object({
    propertyInfo: z.union([
        zOfferDetailsPropertyInfo,
        z.null()
    ]).optional(),
    availability: z.union([
        zHotelAvailabilityStatus,
        z.null()
    ]).optional(),
    roomType: z.union([
        zOfferDetailsRoomType,
        z.null()
    ]).optional(),
    ratePlan: z.union([
        zOfferDetailsRatePlan,
        z.null()
    ]).optional(),
    offer: z.union([
        zOffer,
        z.null()
    ]).optional()
});

/**
 * UniqueID
 *
 * Unique ID definition.
 */
export const zUniqueId = z.object({
    id: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * CancelReservationDetails
 *
 * Details of a canceled reservation.
 */
export const zCancelReservationDetails = z.object({
    reservationIdList: z.union([
        z.array(zUniqueId),
        z.null()
    ]).optional(),
    cancellationNumber: z.union([
        zUniqueId,
        z.null()
    ]).optional(),
    status: z.union([
        z.string(),
        z.null()
    ]).optional().default('Cancelled')
});

/**
 * ProfileInfo
 *
 * Profile info containing profile details.
 */
export const zProfileInfo = z.object({
    profileIdList: z.union([
        z.array(zUniqueId),
        z.null()
    ]).optional(),
    profile: z.union([
        zProfile,
        z.null()
    ]).optional()
});

/**
 * ReservationGuest
 *
 * Guest associated with a reservation.
 */
export const zReservationGuestInput = z.object({
    profileInfo: z.union([
        zProfileInfo,
        z.null()
    ]).optional(),
    primary: z.union([
        z.boolean(),
        z.null()
    ]).optional().default(true)
});

/**
 * Reservation
 *
 * Reservation model.
 */
export const zReservationInput = z.object({
    reservationIdList: z.union([
        z.array(zUniqueId),
        z.null()
    ]).optional(),
    roomStay: z.union([
        zRoomStayInput,
        z.null()
    ]).optional(),
    reservationGuests: z.union([
        z.array(zReservationGuestInput),
        z.null()
    ]).optional(),
    hotelId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reservationStatus: z.union([
        z.string(),
        z.null()
    ]).optional(),
    createDateTime: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

/**
 * CreateReservationRequest
 *
 * Request to create a reservation.
 */
export const zCreateReservationRequest = z.object({
    reservations: z.record(z.array(zReservationInput))
});

/**
 * ReservationGuest
 *
 * Guest associated with a reservation.
 */
export const zReservationGuestOutput = z.object({
    profileInfo: z.union([
        zProfileInfo,
        z.null()
    ]).optional(),
    primary: z.union([
        z.boolean(),
        z.null()
    ]).optional().default(true)
});

/**
 * Reservation
 *
 * Reservation model.
 */
export const zReservationOutput = z.object({
    reservationIdList: z.union([
        z.array(zUniqueId),
        z.null()
    ]).optional(),
    roomStay: z.union([
        zRoomStayOutput,
        z.null()
    ]).optional(),
    reservationGuests: z.union([
        z.array(zReservationGuestOutput),
        z.null()
    ]).optional(),
    hotelId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reservationStatus: z.union([
        z.string(),
        z.null()
    ]).optional(),
    createDateTime: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

/**
 * ReservationListResponse
 *
 * Response containing a list of reservations.
 */
export const zReservationListResponse = z.object({
    reservations: z.union([
        z.record(z.array(zReservationOutput)),
        z.null()
    ]).optional()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.number().int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * Address
 *
 * Address information.
 */
export const zOperaclone2WebApiContentSchemaAddress = z.object({
    lines: z.union([
        z.array(z.string()),
        z.null()
    ]).optional(),
    city: z.union([
        z.string(),
        z.null()
    ]).optional(),
    postalCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    countryCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    state: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * ContentPropertyInfo
 *
 * Property information details.
 */
export const zContentPropertyInfo = z.object({
    hotelId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    enterpriseId: z.union([
        z.string(),
        z.null()
    ]).optional(),
    hotelCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    hotelName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    hotelDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    chainCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    clusterCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    address: z.union([
        zOperaclone2WebApiContentSchemaAddress,
        z.null()
    ]).optional(),
    latitude: z.union([
        z.number(),
        z.null()
    ]).optional(),
    longitude: z.union([
        z.number(),
        z.null()
    ]).optional(),
    propertyAmenities: z.union([
        z.array(zPropertyOffersHotelAmenity),
        z.null()
    ]).optional(),
    pointOfInterest: z.union([
        z.array(zOfferPointOfInterest),
        z.null()
    ]).optional(),
    marketingMessage: z.union([
        z.string(),
        z.null()
    ]).optional(),
    currencyCode: z.union([
        z.string(),
        z.null()
    ]).optional(),
    primaryLanguage: z.union([
        z.string(),
        z.null()
    ]).optional(),
    totalNumberOfRooms: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    petPolicy: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * PropertyInfoResponse
 *
 * Response for property information.
 */
export const zPropertyInfoResponse = z.object({
    propertyInfo: z.union([
        zContentPropertyInfo,
        z.null()
    ]).optional()
});

/**
 * PropertySnippet
 *
 * Snippet information for property summary.
 */
export const zPropertySnippet = z.object({
    hotelId: z.string(),
    hotelCode: z.string(),
    hotelName: z.union([
        z.string(),
        z.null()
    ]).optional(),
    hotelDescription: z.union([
        z.string(),
        z.null()
    ]).optional(),
    address: zOperaclone2WebApiContentSchemaAddress.optional().default({}),
    coordinates: z.record(z.number()).optional().default({}),
    connectivity: z.record(z.string()).optional().default({}),
    meta: z.record(z.unknown()).optional().default({})
});

/**
 * PropertyInfoSummaryResponse
 *
 * Response for property info summary.
 */
export const zPropertyInfoSummaryResponse = z.object({
    hasMore: z.boolean().optional().default(true),
    totalResults: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    limit: z.number().int().optional().default(20),
    count: z.number().int().optional().default(20),
    offset: z.number().int().optional().default(0),
    hotels: z.array(zPropertySnippet).optional().default([])
});

export const zHealthCheckApiHealthGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zSendEchoMessageApiEchoPostData = z.object({
    body: zMessage,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zSendEchoMessageApiEchoPostResponse = zMessage;

export const zGetDummyModelsApiDummyGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        limit: z.number().int().optional().default(10),
        offset: z.number().int().optional().default(0)
    }).optional()
});

/**
 * Response Get Dummy Models Api Dummy  Get
 *
 * Successful Response
 */
export const zGetDummyModelsApiDummyGetResponse = z.array(zDummyModelDto);

export const zCreateDummyModelApiDummyPutData = z.object({
    body: zDummyModelInputDto,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetPropertiesApiShopV1HotelsGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        HotelCodes: z.string(),
        ArrivalDate: z.string().date(),
        ArrivalDateTo: z.union([
            z.string().date(),
            z.null()
        ]).optional(),
        DepartureDate: z.string().date(),
        Adults: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(1),
        Children: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(0),
        ChildrenAges: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RatePlanCodes: z.union([
            z.string(),
            z.null()
        ]).optional(),
        AccessCode: z.union([
            z.string(),
            z.null()
        ]).optional(),
        NumberOfUnits: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(1),
        RateMode: z.union([
            z.string(),
            z.null()
        ]).optional().default('Highest'),
        RatePlanCodeMatchOnly: z.union([
            z.boolean(),
            z.null()
        ]).optional().default(false),
        RatePlanType: z.union([
            z.string(),
            z.null()
        ]).optional(),
        AvailableOnly: z.union([
            z.boolean(),
            z.null()
        ]).optional().default(false),
        minRate: z.union([
            z.number(),
            z.null()
        ]).optional(),
        maxRate: z.union([
            z.number(),
            z.null()
        ]).optional(),
        AlternateOffers: z.union([
            z.string(),
            z.null()
        ]).optional().default('Always'),
        CommissionableStatus: z.union([
            z.string(),
            z.null()
        ]).optional().default('Both'),
        PromotionCodes: z.union([
            z.string(),
            z.null()
        ]).optional()
    }),
    headers: z.object({
        authorization: z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-channelCode': z.string(),
        'x-app-key': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'Accept-Language': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-request-id': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-originating-application': z.union([
            z.string(),
            z.null()
        ]).optional()
    })
});

/**
 * Successful Response
 */
export const zGetPropertiesApiShopV1HotelsGetResponse = zPropertySearchResponse;

export const zGetPropertyOffersApiShopV1HotelsHotelCodeOffersGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.object({
        ArrivalDate: z.string().date(),
        DepartureDate: z.string().date(),
        Adults: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(1),
        Children: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(0),
        ChildrenAges: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RoomTypes: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RatePlanCodes: z.union([
            z.string(),
            z.null()
        ]).optional(),
        AccessCode: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RatePlanType: z.union([
            z.string(),
            z.null()
        ]).optional(),
        NumberOfUnits: z.union([
            z.number().int(),
            z.null()
        ]).optional(),
        RoomTypeMatchOnly: z.union([
            z.boolean(),
            z.null()
        ]).optional(),
        RatePlanCodeMatchOnly: z.union([
            z.boolean(),
            z.null()
        ]).optional(),
        RateMode: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RoomAmenity: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RoomAmenityQuantity: z.union([
            z.number().int(),
            z.null()
        ]).optional(),
        IncludeAmenities: z.union([
            z.boolean(),
            z.null()
        ]).optional(),
        minRate: z.union([
            z.number(),
            z.null()
        ]).optional(),
        maxRate: z.union([
            z.number(),
            z.null()
        ]).optional(),
        AlternateOffers: z.union([
            z.string(),
            z.null()
        ]).optional(),
        CommissionableStatus: z.union([
            z.string(),
            z.null()
        ]).optional(),
        PromotionCodes: z.union([
            z.string(),
            z.null()
        ]).optional(),
        BlockCode: z.union([
            z.string(),
            z.null()
        ]).optional()
    }),
    headers: z.object({
        authorization: z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-channelCode': z.string(),
        'x-app-key': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'Accept-Language': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-request-id': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-originating-application': z.union([
            z.string(),
            z.null()
        ]).optional()
    })
});

/**
 * Successful Response
 */
export const zGetPropertyOffersApiShopV1HotelsHotelCodeOffersGetResponse = zPropertyOffersResponse;

export const zGetPropertyOfferApiShopV1HotelsHotelCodeOfferGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.object({
        ArrivalDate: z.string().date(),
        DepartureDate: z.string().date(),
        Adults: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(1),
        Children: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(0),
        ChildrenAges: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RoomType: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RatePlanCode: z.union([
            z.string(),
            z.null()
        ]).optional(),
        AccessCode: z.union([
            z.string(),
            z.null()
        ]).optional(),
        RateMode: z.union([
            z.string(),
            z.null()
        ]).optional(),
        NumberOfUnits: z.union([
            z.number().int(),
            z.null()
        ]).optional(),
        BookingCode: z.union([
            z.string(),
            z.null()
        ]).optional(),
        IncludeAmenities: z.union([
            z.boolean(),
            z.null()
        ]).optional(),
        PromotionCodes: z.union([
            z.string(),
            z.null()
        ]).optional(),
        BlockCode: z.union([
            z.string(),
            z.null()
        ]).optional()
    }),
    headers: z.object({
        authorization: z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-externalsystem': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-app-key': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-channelCode': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'Accept-Language': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-request-id': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-originating-application': z.union([
            z.string(),
            z.null()
        ]).optional()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetPropertyOfferApiShopV1HotelsHotelCodeOfferGetResponse = zOfferDetailsResponse;

export const zGetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        hotelId: z.string().min(1).max(2000)
    }),
    query: z.object({
        dateRangeStart: z.string().date(),
        dateRangeEnd: z.string().date(),
        reportCode: z.enum([
            'DetailedAvailabiltySummary',
            'RoomCalendarStatistics',
            'SellLimitSummary',
            'RoomsAvailabilitySummary'
        ]),
        parameterName: z.union([
            z.array(z.string()),
            z.null()
        ]).optional(),
        parameterValue: z.union([
            z.array(z.string()),
            z.null()
        ]).optional()
    })
});

/**
 * Response Get Inventory Statistics Api Inv V1 Hotels  Hotelid  Inventorystatistics Get
 *
 * Successful Response
 */
export const zGetInventoryStatisticsApiInvV1HotelsHotelIdInventoryStatisticsGetResponse = z.array(zStatisticType);

export const zGetPropertiesSummaryApiContentV1HotelsGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        connectionStatusLastChangedFrom: z.union([
            z.string().datetime(),
            z.null()
        ]).optional(),
        connectionStatusLastChangedTo: z.union([
            z.string().datetime(),
            z.null()
        ]).optional(),
        connectionStatus: z.union([
            z.string(),
            z.null()
        ]).optional(),
        fetchInstructions: z.union([
            z.string(),
            z.null()
        ]).optional(),
        limit: z.number().int().optional().default(20),
        offset: z.number().int().optional().default(0)
    }).optional(),
    headers: z.object({
        authorization: z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-channelCode': z.string(),
        'x-app-key': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-request-id': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-originating-application': z.union([
            z.string(),
            z.null()
        ]).optional()
    })
});

/**
 * Successful Response
 */
export const zGetPropertiesSummaryApiContentV1HotelsGetResponse = zPropertyInfoSummaryResponse;

export const zGetPropertyInfoApiContentV1HotelsHotelCodeGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.never().optional(),
    headers: z.object({
        authorization: z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-channelCode': z.string(),
        'x-app-key': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-request-id': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-originating-application': z.union([
            z.string(),
            z.null()
        ]).optional()
    })
});

/**
 * Successful Response
 */
export const zGetPropertyInfoApiContentV1HotelsHotelCodeGetResponse = zPropertyInfoResponse;

export const zGetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.object({
        includeRoomAmenities: z.union([
            z.boolean(),
            z.null()
        ]).optional().default(false),
        roomType: z.union([
            z.string(),
            z.null()
        ]).optional(),
        limit: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(20),
        offset: z.union([
            z.number().int(),
            z.null()
        ]).optional().default(0)
    }).optional(),
    headers: z.object({
        authorization: z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-channelCode': z.string(),
        'x-app-key': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-request-id': z.union([
            z.string(),
            z.null()
        ]).optional(),
        'x-originating-application': z.union([
            z.string(),
            z.null()
        ]).optional()
    })
});

/**
 * Successful Response
 */
export const zGetRoomTypesInfoApiContentV1HotelsHotelCodeRoomTypesGetResponse = zRoomTypesResponse;

export const zGetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.object({
        surname: z.union([
            z.string(),
            z.null()
        ]).optional(),
        givenName: z.union([
            z.string(),
            z.null()
        ]).optional(),
        arrivalStartDate: z.union([
            z.string().date(),
            z.null()
        ]).optional(),
        arrivalEndDate: z.union([
            z.string().date(),
            z.null()
        ]).optional(),
        confirmationNumberList: z.union([
            z.array(z.string()),
            z.null()
        ]).optional(),
        limit: z.number().int().optional().default(100),
        offset: z.number().int().optional().default(0)
    }).optional()
});

/**
 * Successful Response
 */
export const zGetHotelReservationsApiRsvV1HotelsHotelIdReservationsGetResponse = zReservationListResponse;

export const zCreateReservationApiRsvV1HotelsHotelIdReservationsPostData = z.object({
    body: zCreateReservationRequest,
    path: z.object({
        hotelId: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCreateReservationApiRsvV1HotelsHotelIdReservationsPostResponse = zReservationListResponse;

export const zGetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.object({
        arrivalDate: z.union([
            z.string().date(),
            z.null()
        ]).optional(),
        lastName: z.union([
            z.string(),
            z.null()
        ]).optional(),
        limit: z.number().int().optional().default(200),
        offset: z.number().int().optional().default(0)
    }).optional()
});

/**
 * Successful Response
 */
export const zGetReservationsSummaryApiRsvV1HotelsHotelIdReservationsSummaryGetResponse = zReservationSummaryResponse;

export const zGetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.object({
        startDate: z.union([
            z.string().date(),
            z.null()
        ]).optional(),
        endDate: z.union([
            z.string().date(),
            z.null()
        ]).optional(),
        limit: z.number().int().optional().default(20),
        offset: z.number().int().optional().default(0)
    }).optional()
});

/**
 * Successful Response
 */
export const zGetReservationStatisticsApiRsvV1HotelsHotelIdReservationsStatisticsGetResponse = zCheckDistributionReservationsSummary;

export const zUpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutData = z.object({
    body: zCreateReservationRequest,
    path: z.object({
        hotelId: z.string(),
        reservationId: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateReservationApiRsvV1HotelsHotelIdReservationsReservationIdPutResponse = zReservationListResponse;

export const zCancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostData = z.object({
    body: zCancelReservationRequest,
    path: z.object({
        hotelId: z.string(),
        reservationId: z.string()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCancelReservationApiRsvV1HotelsHotelIdReservationsReservationIdCancellationsPostResponse = zCancelReservationDetails;
