// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiBookingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bookings';
};

export type GetApiBookingsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id?: string;
        partnerId?: string;
        customerName?: string;
        serviceType?: string;
        startDate?: string;
        endDate?: string;
        status?: string;
        createdAt?: string;
        updatedAt?: string;
    }>;
};

export type GetApiBookingsResponse = GetApiBookingsResponses[keyof GetApiBookingsResponses];

export type PostApiBookingsData = {
    body: {
        partnerId: string;
        customerName: string;
        serviceType: string;
        startDate: string;
        endDate: string;
    };
    path?: never;
    query?: never;
    url: '/api/bookings';
};

export type PostApiBookingsResponses = {
    /**
     * Default Response
     */
    201: {
        id?: string;
        partnerId?: string;
        customerName?: string;
        serviceType?: string;
        startDate?: string;
        endDate?: string;
        status?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type PostApiBookingsResponse = PostApiBookingsResponses[keyof PostApiBookingsResponses];

export type DeleteApiBookingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}';
};

export type DeleteApiBookingsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error?: string;
    };
};

export type DeleteApiBookingsByIdError = DeleteApiBookingsByIdErrors[keyof DeleteApiBookingsByIdErrors];

export type DeleteApiBookingsByIdResponses = {
    /**
     * Default Response
     */
    204: void;
};

export type DeleteApiBookingsByIdResponse = DeleteApiBookingsByIdResponses[keyof DeleteApiBookingsByIdResponses];

export type GetApiBookingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}';
};

export type GetApiBookingsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error?: string;
    };
};

export type GetApiBookingsByIdError = GetApiBookingsByIdErrors[keyof GetApiBookingsByIdErrors];

export type GetApiBookingsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id?: string;
        partnerId?: string;
        customerName?: string;
        serviceType?: string;
        startDate?: string;
        endDate?: string;
        status?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type GetApiBookingsByIdResponse = GetApiBookingsByIdResponses[keyof GetApiBookingsByIdResponses];

export type PutApiBookingsByIdData = {
    body?: {
        customerName?: string;
        status?: 'pending' | 'confirmed' | 'cancelled' | 'completed';
        startDate?: string;
        endDate?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}';
};

export type PutApiBookingsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error?: string;
    };
};

export type PutApiBookingsByIdError = PutApiBookingsByIdErrors[keyof PutApiBookingsByIdErrors];

export type PutApiBookingsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id?: string;
        partnerId?: string;
        customerName?: string;
        serviceType?: string;
        startDate?: string;
        endDate?: string;
        status?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type PutApiBookingsByIdResponse = PutApiBookingsByIdResponses[keyof PutApiBookingsByIdResponses];

export type GetApiHotelsAvailabilityData = {
    body?: never;
    path?: never;
    query: {
        /**
         * List of Hotel Codes (CSV)
         */
        hotelCodes: string;
        arrivalDate: string;
        arrivalDateTo?: string;
        departureDate: string;
        adults?: number;
        children?: number;
        childrenAges?: string;
        ratePlanCodes?: string;
        accessCode?: string;
        numberOfUnits?: number;
        rateMode?: string;
        ratePlanCodeMatchOnly?: boolean;
        ratePlanType?: string;
        availableOnly?: boolean;
        minRate?: number;
        maxRate?: number;
        alternateOffers?: string;
        commissionableStatus?: string;
        promotionCodes?: string;
    };
    url: '/api/hotels/availability';
};

export type GetApiHotelsAvailabilityErrors = {
    /**
     * Default Response
     */
    400: {
        error?: string;
        details?: Array<unknown>;
    };
};

export type GetApiHotelsAvailabilityError = GetApiHotelsAvailabilityErrors[keyof GetApiHotelsAvailabilityErrors];

export type GetApiHotelsAvailabilityResponses = {
    /**
     * Default Response
     */
    200: {
        roomStays?: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type GetApiHotelsAvailabilityResponse = GetApiHotelsAvailabilityResponses[keyof GetApiHotelsAvailabilityResponses];

export type GetApiHotelsByHotelCodeOffersData = {
    body?: never;
    path: {
        hotelCode: string;
    };
    query: {
        arrivalDate: string;
        departureDate: string;
        adults?: number;
        children?: number;
        childrenAges?: string;
        roomTypes?: string;
        ratePlanCodes?: string;
        accessCode?: string;
        ratePlanType?: string;
        numberOfUnits?: number;
        roomTypeMatchOnly?: boolean;
        ratePlanCodeMatchOnly?: boolean;
        rateMode?: string;
        roomAmenity?: string;
        roomAmenityQuantity?: number;
        includeAmenities?: boolean;
        minRate?: number;
        maxRate?: number;
        alternateOffers?: string;
        commissionableStatus?: string;
        promotionCodes?: string;
        blockCode?: string;
    };
    url: '/api/hotels/{hotelCode}/offers';
};

export type GetApiHotelsByHotelCodeOffersErrors = {
    /**
     * Default Response
     */
    400: {
        error?: string;
        details?: Array<unknown>;
    };
};

export type GetApiHotelsByHotelCodeOffersError = GetApiHotelsByHotelCodeOffersErrors[keyof GetApiHotelsByHotelCodeOffersErrors];

export type GetApiHotelsByHotelCodeOffersResponses = {
    /**
     * Default Response
     */
    200: {
        roomStays?: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type GetApiHotelsByHotelCodeOffersResponse = GetApiHotelsByHotelCodeOffersResponses[keyof GetApiHotelsByHotelCodeOffersResponses];

export type GetApiHotelsByHotelCodeOfferData = {
    body?: never;
    path: {
        hotelCode: string;
    };
    query: {
        arrivalDate: string;
        departureDate: string;
        adults?: number;
        children?: number;
        childrenAges?: string;
        roomType?: string;
        ratePlanCode?: string;
        accessCode?: string;
        rateMode?: string;
        numberOfUnits?: number;
        bookingCode?: string;
        includeAmenities?: boolean;
        promotionCodes?: string;
        blockCode?: string;
    };
    url: '/api/hotels/{hotelCode}/offer';
};

export type GetApiHotelsByHotelCodeOfferErrors = {
    /**
     * Default Response
     */
    400: {
        error?: string;
        details?: Array<unknown>;
    };
};

export type GetApiHotelsByHotelCodeOfferError = GetApiHotelsByHotelCodeOfferErrors[keyof GetApiHotelsByHotelCodeOfferErrors];

export type GetApiHotelsByHotelCodeOfferResponses = {
    /**
     * Default Response
     */
    200: {
        propertyInfo?: {
            [key: string]: unknown;
        };
        availability?: string;
        roomType?: {
            [key: string]: unknown;
        };
        ratePlan?: {
            [key: string]: unknown;
        };
        offer?: {
            [key: string]: unknown;
        };
    };
};

export type GetApiHotelsByHotelCodeOfferResponse = GetApiHotelsByHotelCodeOfferResponses[keyof GetApiHotelsByHotelCodeOfferResponses];
