// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiBookingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bookings';
};

export type GetApiBookingsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id?: string;
        partnerId?: string;
        customerName?: string;
        serviceType?: string;
        startDate?: string;
        endDate?: string;
        status?: string;
        createdAt?: string;
        updatedAt?: string;
    }>;
};

export type GetApiBookingsResponse = GetApiBookingsResponses[keyof GetApiBookingsResponses];

export type PostApiBookingsData = {
    body: {
        partnerId: string;
        customerName: string;
        serviceType: string;
        startDate: string;
        endDate: string;
    };
    path?: never;
    query?: never;
    url: '/api/bookings';
};

export type PostApiBookingsResponses = {
    /**
     * Default Response
     */
    201: {
        id?: string;
        partnerId?: string;
        customerName?: string;
        serviceType?: string;
        startDate?: string;
        endDate?: string;
        status?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type PostApiBookingsResponse = PostApiBookingsResponses[keyof PostApiBookingsResponses];

export type DeleteApiBookingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}';
};

export type DeleteApiBookingsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error?: string;
    };
};

export type DeleteApiBookingsByIdError = DeleteApiBookingsByIdErrors[keyof DeleteApiBookingsByIdErrors];

export type DeleteApiBookingsByIdResponses = {
    /**
     * Default Response
     */
    204: void;
};

export type DeleteApiBookingsByIdResponse = DeleteApiBookingsByIdResponses[keyof DeleteApiBookingsByIdResponses];

export type GetApiBookingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}';
};

export type GetApiBookingsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error?: string;
    };
};

export type GetApiBookingsByIdError = GetApiBookingsByIdErrors[keyof GetApiBookingsByIdErrors];

export type GetApiBookingsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id?: string;
        partnerId?: string;
        customerName?: string;
        serviceType?: string;
        startDate?: string;
        endDate?: string;
        status?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type GetApiBookingsByIdResponse = GetApiBookingsByIdResponses[keyof GetApiBookingsByIdResponses];

export type PutApiBookingsByIdData = {
    body?: {
        customerName?: string;
        status?: 'pending' | 'confirmed' | 'cancelled' | 'completed';
        startDate?: string;
        endDate?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/bookings/{id}';
};

export type PutApiBookingsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error?: string;
    };
};

export type PutApiBookingsByIdError = PutApiBookingsByIdErrors[keyof PutApiBookingsByIdErrors];

export type PutApiBookingsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id?: string;
        partnerId?: string;
        customerName?: string;
        serviceType?: string;
        startDate?: string;
        endDate?: string;
        status?: string;
        createdAt?: string;
        updatedAt?: string;
    };
};

export type PutApiBookingsByIdResponse = PutApiBookingsByIdResponses[keyof PutApiBookingsByIdResponses];
