// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zGetApiBookingsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zGetApiBookingsResponse = z.array(z.object({
    id: z.optional(z.string()),
    partnerId: z.optional(z.string()),
    customerName: z.optional(z.string()),
    serviceType: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    status: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    updatedAt: z.optional(z.string())
}));

export const zPostApiBookingsData = z.object({
    body: z.object({
        partnerId: z.string(),
        customerName: z.string(),
        serviceType: z.string(),
        startDate: z.iso.datetime(),
        endDate: z.iso.datetime()
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zPostApiBookingsResponse = z.object({
    id: z.optional(z.string()),
    partnerId: z.optional(z.string()),
    customerName: z.optional(z.string()),
    serviceType: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    status: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    updatedAt: z.optional(z.string())
});

export const zDeleteApiBookingsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zDeleteApiBookingsByIdResponse = z.void();

export const zGetApiBookingsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zGetApiBookingsByIdResponse = z.object({
    id: z.optional(z.string()),
    partnerId: z.optional(z.string()),
    customerName: z.optional(z.string()),
    serviceType: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    status: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    updatedAt: z.optional(z.string())
});

export const zPutApiBookingsByIdData = z.object({
    body: z.optional(z.object({
        customerName: z.optional(z.string()),
        status: z.optional(z.enum([
            'pending',
            'confirmed',
            'cancelled',
            'completed'
        ])),
        startDate: z.optional(z.iso.datetime()),
        endDate: z.optional(z.iso.datetime())
    })),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zPutApiBookingsByIdResponse = z.object({
    id: z.optional(z.string()),
    partnerId: z.optional(z.string()),
    customerName: z.optional(z.string()),
    serviceType: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    status: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    updatedAt: z.optional(z.string())
});
