// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zGetApiBookingsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zGetApiBookingsResponse = z.array(z.object({
    id: z.optional(z.string()),
    partnerId: z.optional(z.string()),
    customerName: z.optional(z.string()),
    serviceType: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    status: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    updatedAt: z.optional(z.string())
}));

export const zPostApiBookingsData = z.object({
    body: z.object({
        partnerId: z.string(),
        customerName: z.string(),
        serviceType: z.string(),
        startDate: z.iso.datetime(),
        endDate: z.iso.datetime()
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zPostApiBookingsResponse = z.object({
    id: z.optional(z.string()),
    partnerId: z.optional(z.string()),
    customerName: z.optional(z.string()),
    serviceType: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    status: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    updatedAt: z.optional(z.string())
});

export const zDeleteApiBookingsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zDeleteApiBookingsByIdResponse = z.void();

export const zGetApiBookingsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zGetApiBookingsByIdResponse = z.object({
    id: z.optional(z.string()),
    partnerId: z.optional(z.string()),
    customerName: z.optional(z.string()),
    serviceType: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    status: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    updatedAt: z.optional(z.string())
});

export const zPutApiBookingsByIdData = z.object({
    body: z.optional(z.object({
        customerName: z.optional(z.string()),
        status: z.optional(z.enum([
            'pending',
            'confirmed',
            'cancelled',
            'completed'
        ])),
        startDate: z.optional(z.iso.datetime()),
        endDate: z.optional(z.iso.datetime())
    })),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zPutApiBookingsByIdResponse = z.object({
    id: z.optional(z.string()),
    partnerId: z.optional(z.string()),
    customerName: z.optional(z.string()),
    serviceType: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    status: z.optional(z.string()),
    createdAt: z.optional(z.string()),
    updatedAt: z.optional(z.string())
});

export const zGetApiHotelsAvailabilityData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        hotelCodes: z.string(),
        arrivalDate: z.iso.date(),
        arrivalDateTo: z.optional(z.iso.date()),
        departureDate: z.iso.date(),
        adults: z.optional(z.int().gte(1)),
        children: z.optional(z.int().gte(0)),
        childrenAges: z.optional(z.string()),
        ratePlanCodes: z.optional(z.string()),
        accessCode: z.optional(z.string()),
        numberOfUnits: z.optional(z.int().gte(1)),
        rateMode: z.optional(z.string()),
        ratePlanCodeMatchOnly: z.optional(z.boolean()),
        ratePlanType: z.optional(z.string()),
        availableOnly: z.optional(z.boolean()),
        minRate: z.optional(z.number()),
        maxRate: z.optional(z.number()),
        alternateOffers: z.optional(z.string()),
        commissionableStatus: z.optional(z.string()),
        promotionCodes: z.optional(z.string())
    })
});

/**
 * Default Response
 */
export const zGetApiHotelsAvailabilityResponse = z.object({
    roomStays: z.optional(z.array(z.record(z.string(), z.unknown())))
});

export const zGetApiHotelsByHotelCodeOffersData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.object({
        arrivalDate: z.iso.date(),
        departureDate: z.iso.date(),
        adults: z.optional(z.int().gte(1)),
        children: z.optional(z.int().gte(0)),
        childrenAges: z.optional(z.string()),
        roomTypes: z.optional(z.string()),
        ratePlanCodes: z.optional(z.string()),
        accessCode: z.optional(z.string()),
        ratePlanType: z.optional(z.string()),
        numberOfUnits: z.optional(z.int().gte(1)),
        roomTypeMatchOnly: z.optional(z.boolean()),
        ratePlanCodeMatchOnly: z.optional(z.boolean()),
        rateMode: z.optional(z.string()),
        roomAmenity: z.optional(z.string()),
        roomAmenityQuantity: z.optional(z.int().gte(0)),
        includeAmenities: z.optional(z.boolean()),
        minRate: z.optional(z.number()),
        maxRate: z.optional(z.number()),
        alternateOffers: z.optional(z.string()),
        commissionableStatus: z.optional(z.string()),
        promotionCodes: z.optional(z.string()),
        blockCode: z.optional(z.string())
    })
});

/**
 * Default Response
 */
export const zGetApiHotelsByHotelCodeOffersResponse = z.object({
    roomStays: z.optional(z.array(z.record(z.string(), z.unknown())))
});

export const zGetApiHotelsByHotelCodeOfferData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.object({
        arrivalDate: z.iso.date(),
        departureDate: z.iso.date(),
        adults: z.optional(z.int().gte(1)),
        children: z.optional(z.int().gte(0)),
        childrenAges: z.optional(z.string()),
        roomType: z.optional(z.string()),
        ratePlanCode: z.optional(z.string()),
        accessCode: z.optional(z.string()),
        rateMode: z.optional(z.string()),
        numberOfUnits: z.optional(z.int().gte(1)),
        bookingCode: z.optional(z.string()),
        includeAmenities: z.optional(z.boolean()),
        promotionCodes: z.optional(z.string()),
        blockCode: z.optional(z.string())
    })
});

/**
 * Default Response
 */
export const zGetApiHotelsByHotelCodeOfferResponse = z.object({
    propertyInfo: z.optional(z.record(z.string(), z.unknown())),
    availability: z.optional(z.string()),
    roomType: z.optional(z.record(z.string(), z.unknown())),
    ratePlan: z.optional(z.record(z.string(), z.unknown())),
    offer: z.optional(z.record(z.string(), z.unknown()))
});

export const zGetApiContentHotelsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        connectionStatusLastChangedFrom: z.optional(z.iso.datetime()),
        connectionStatusLastChangedTo: z.optional(z.iso.datetime()),
        connectionStatus: z.optional(z.string()),
        fetchInstructions: z.optional(z.string()),
        limit: z.optional(z.int()).default(20),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Default Response
 */
export const zGetApiContentHotelsResponse = z.object({
    hasMore: z.optional(z.boolean()),
    totalResults: z.optional(z.int()),
    limit: z.optional(z.int()),
    count: z.optional(z.int()),
    offset: z.optional(z.int()),
    hotels: z.optional(z.array(z.object({
        hotelId: z.optional(z.string()),
        hotelCode: z.optional(z.string()),
        hotelName: z.optional(z.string()),
        hotelDescription: z.optional(z.string())
    })))
});

export const zGetApiContentHotelsByHotelCodeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zGetApiContentHotelsByHotelCodeResponse = z.object({
    propertyInfo: z.optional(z.object({
        hotelId: z.optional(z.string()),
        enterpriseId: z.optional(z.string()),
        hotelCode: z.optional(z.string()),
        hotelName: z.optional(z.string()),
        hotelDescription: z.optional(z.string()),
        chainCode: z.optional(z.string())
    }))
});

export const zGetApiContentHotelsByHotelCodeRoomTypesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelCode: z.string()
    }),
    query: z.optional(z.object({
        includeRoomAmenities: z.optional(z.boolean()).default(false),
        roomType: z.optional(z.string()),
        limit: z.optional(z.int()).default(20),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Default Response
 */
export const zGetApiContentHotelsByHotelCodeRoomTypesResponse = z.object({
    roomTypes: z.optional(z.array(z.object({
        hotelRoomType: z.optional(z.string()),
        roomType: z.optional(z.string()),
        roomName: z.optional(z.string())
    }))),
    count: z.optional(z.int()),
    hasMore: z.optional(z.boolean()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    totalResults: z.optional(z.int())
});

export const zGetApiHotelsByHotelIdReservationsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.optional(z.object({
        surname: z.optional(z.string()),
        givenName: z.optional(z.string()),
        arrivalStartDate: z.optional(z.iso.date()),
        arrivalEndDate: z.optional(z.iso.date()),
        confirmationNumberList: z.optional(z.array(z.string())),
        limit: z.optional(z.int()).default(100),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Default Response
 */
export const zGetApiHotelsByHotelIdReservationsResponse = z.object({
    reservations: z.optional(z.object({
        reservation: z.optional(z.array(z.record(z.string(), z.unknown())))
    }))
});

export const zPostApiHotelsByHotelIdReservationsData = z.object({
    body: z.optional(z.record(z.string(), z.unknown())),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zPostApiHotelsByHotelIdReservationsResponse = z.record(z.string(), z.unknown());

export const zGetApiHotelsByHotelIdReservationsSummaryData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.optional(z.object({
        arrivalDate: z.optional(z.iso.date()),
        lastName: z.optional(z.string()),
        limit: z.optional(z.int()).default(200),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Default Response
 */
export const zGetApiHotelsByHotelIdReservationsSummaryResponse = z.record(z.string(), z.unknown());

export const zGetApiHotelsByHotelIdReservationsStatisticsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        hotelId: z.string()
    }),
    query: z.optional(z.object({
        startDate: z.optional(z.iso.date()),
        endDate: z.optional(z.iso.date()),
        limit: z.optional(z.int()).default(20),
        offset: z.optional(z.int()).default(0)
    }))
});

/**
 * Default Response
 */
export const zGetApiHotelsByHotelIdReservationsStatisticsResponse = z.record(z.string(), z.unknown());

export const zPutApiHotelsByHotelIdReservationsByReservationIdData = z.object({
    body: z.optional(z.record(z.string(), z.unknown())),
    path: z.object({
        hotelId: z.string(),
        reservationId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zPutApiHotelsByHotelIdReservationsByReservationIdResponse = z.record(z.string(), z.unknown());

export const zPostApiHotelsByHotelIdReservationsByReservationIdCancellationsData = z.object({
    body: z.optional(z.record(z.string(), z.unknown())),
    path: z.object({
        hotelId: z.string(),
        reservationId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Default Response
 */
export const zPostApiHotelsByHotelIdReservationsByReservationIdCancellationsResponse = z.record(z.string(), z.unknown());
