"""empty message.

Revision ID: bbb754b68872
Revises: 2b7380507a71
Create Date: 2026-01-21 17:11:12.973597

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bbb754b68872"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("hotels",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("hotel_id", sa.String(length=50), nullable=False, comment="Internal ID like SBOXD1"),
    sa.Column("hotel_code", sa.String(length=50), nullable=False, comment="Channel specific code like XSBOXD1"),
    sa.Column("enterprise_id", sa.String(length=50), nullable=True),
    sa.Column("chain_code", sa.String(length=20), nullable=True),
    sa.Column("cluster_code", sa.String(length=20), nullable=True),
    sa.Column("hotel_name", sa.String(length=200), nullable=True),
    sa.Column("hotel_description", sa.Text(), nullable=True),
    sa.Column("city_name", sa.String(length=100), nullable=True),
    sa.Column("country_code", sa.String(length=10), nullable=True),
    sa.Column("state_prov", sa.String(length=50), nullable=True),
    sa.Column("postal_code", sa.String(length=20), nullable=True),
    sa.Column("address_lines", sa.JSON(), nullable=True, comment="List of address lines"),
    sa.Column("latitude", sa.Float(), nullable=True),
    sa.Column("longitude", sa.Float(), nullable=True),
    sa.Column("currency_code", sa.String(length=3), nullable=True),
    sa.Column("primary_language", sa.String(length=10), nullable=True),
    sa.Column("total_number_of_rooms", sa.Integer(), nullable=True),
    sa.Column("pet_policy", sa.String(length=255), nullable=True),
    sa.Column("time_zone_name", sa.String(length=100), nullable=True, comment="e.g. US/Eastern"),
    sa.Column("time_zone_offset", sa.String(length=20), nullable=True, comment="e.g. UTC-04:00"),
    sa.Column("check_in_time", sa.String(length=10), nullable=True, comment="e.g. 15:00"),
    sa.Column("check_out_time", sa.String(length=10), nullable=True, comment="e.g. 11:00"),
    sa.Column("property_amenities", sa.JSON(), nullable=True),
    sa.Column("point_of_interest", sa.JSON(), nullable=True),
    sa.Column("communications", sa.JSON(), nullable=True),
    sa.Column("transportations", sa.JSON(), nullable=True),
    sa.Column("hotel_child_policy", sa.JSON(), nullable=True),
    sa.Column("direction_info", sa.Text(), nullable=True, comment="Maps to direction.propertyDirection"),
    sa.Column("location_info", sa.Text(), nullable=True, comment="Maps to location.propertyLocation"),
    sa.Column("meta", sa.JSON(), nullable=True, comment="Extra metadata not covered by standard schema"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_hotels_city_name"), "hotels", ["city_name"], unique=False)
    op.create_index(op.f("ix_hotels_hotel_code"), "hotels", ["hotel_code"], unique=False)
    op.create_index(op.f("ix_hotels_hotel_id"), "hotels", ["hotel_id"], unique=True)
    op.alter_column("dummy_model", "name",
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dummy_model", "name",
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index(op.f("ix_hotels_hotel_id"), table_name="hotels")
    op.drop_index(op.f("ix_hotels_hotel_code"), table_name="hotels")
    op.drop_index(op.f("ix_hotels_city_name"), table_name="hotels")
    op.drop_table("hotels")
    # ### end Alembic commands ###
