"""add_room_types_table.

Revision ID: 4cd425d0265a
Revises: bbb754b68872
Create Date: 2026-01-22 06:30:26.202160

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4cd425d0265a"
down_revision = "bbb754b68872"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("room_types",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("hotel_id_fk", sa.Integer(), nullable=False),
    sa.Column("hotel_room_type", sa.String(length=50), nullable=True),
    sa.Column("room_type", sa.String(length=50), nullable=True),
    sa.Column("description", sa.JSON(), nullable=True),
    sa.Column("room_name", sa.String(length=200), nullable=True),
    sa.Column("room_category", sa.String(length=50), nullable=True),
    sa.Column("room_amenities", sa.JSON(), nullable=True),
    sa.Column("room_view_type", sa.String(length=50), nullable=True),
    sa.Column("room_primary_bed_type", sa.String(length=50), nullable=True),
    sa.Column("non_smoking_ind", sa.Boolean(), nullable=True),
    sa.Column("occupancy", sa.JSON(), nullable=True),
    sa.Column("number_of_units", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["hotel_id_fk"], ["hotels.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_room_types_hotel_id_fk"), "room_types", ["hotel_id_fk"], unique=False)
    op.create_index(op.f("ix_room_types_room_type"), "room_types", ["room_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_types_room_type"), table_name="room_types")
    op.drop_index(op.f("ix_room_types_hotel_id_fk"), table_name="room_types")
    op.drop_table("room_types")
    # ### end Alembic commands ###
