"""empty message.

Revision ID: 97a9d00aafe4
Revises: bf0120e3f042
Create Date: 2026-01-22 17:25:35.959631

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "97a9d00aafe4"
down_revision = "bf0120e3f042"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("reservations",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("reservation_id", sa.String(length=50), nullable=False),
    sa.Column("confirmation_number", sa.String(length=50), nullable=True),
    sa.Column("hotel_id", sa.String(length=50), nullable=False),
    sa.Column("reservation_status", sa.String(length=20), nullable=False),
    sa.Column("arrival_date", sa.Date(), nullable=False),
    sa.Column("departure_date", sa.Date(), nullable=False),
    sa.Column("guest_first_name", sa.String(length=100), nullable=True),
    sa.Column("guest_last_name", sa.String(length=100), nullable=True),
    sa.Column("room_stay", sa.JSON(), nullable=False),
    sa.Column("reservation_guests", sa.JSON(), nullable=False),
    sa.Column("create_date_time", sa.DateTime(), nullable=False),
    sa.Column("update_date_time", sa.DateTime(), nullable=False),
    sa.Column("cancellation_number", sa.String(length=50), nullable=True),
    sa.Column("cancellation_reason_code", sa.String(length=20), nullable=True),
    sa.Column("cancellation_reason_desc", sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_reservations_arrival_date"), "reservations", ["arrival_date"], unique=False)
    op.create_index(op.f("ix_reservations_confirmation_number"), "reservations", ["confirmation_number"], unique=False)
    op.create_index(op.f("ix_reservations_departure_date"), "reservations", ["departure_date"], unique=False)
    op.create_index(op.f("ix_reservations_guest_last_name"), "reservations", ["guest_last_name"], unique=False)
    op.create_index(op.f("ix_reservations_hotel_id"), "reservations", ["hotel_id"], unique=False)
    op.create_index(op.f("ix_reservations_reservation_id"), "reservations", ["reservation_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservations_reservation_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_hotel_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_guest_last_name"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_departure_date"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_confirmation_number"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_arrival_date"), table_name="reservations")
    op.drop_table("reservations")
    # ### end Alembic commands ###
